export const content = {
  "en": {
    "skip": "Skip to content",
    "navSolution": "Solutions",
    "navTech": "How we build",
    "navProjects": "Applications",
    "navContact": "Consult your project",
    "menu": "Open menu",
    "close": "Close",
    "brandSub": "AFFORDABLE DEVELOPMENT",
    "group": "PART OF THE GROUP",
    "heroEyebrow": "FJÄLL AFFORDABLE DEVELOPMENT",
    "heroTitle": "Build smarter.",
    "heroAccent": "Scale further.",
    "heroDescription": "Mass-scale development, built on a repeatable system. From residential communities to learning spaces and workforce accommodation, align the design and specification once — then plan your rollout with confidence.",
    "heroCta": "Let’s talk about your project",
    "heroSecondary": "Explore our solutions",
    "heroTag": "For developers, government programmes & institutions",
    "heroCaption": "ILLUSTRATIVE DEVELOPMENT CONCEPT",
    "heroCardTitle": "One building system. Many possibilities.",
    "heroCardText": "Housing · Education · Accommodation",
    "metric1": "Standard home footprint",
    "metric2": "Superstructure assembly¹",
    "metric3": "Lightweight structure¹",
    "introLabel": "THE FAD ADVANTAGE",
    "introTitle": "A smarter way to build.",
    "introAccent": "A system designed to scale.",
    "introText": "Think beyond a single building. FAD brings a standardised composite build system to developments with multiple units, uses, and delivery phases. Start with your brief. Define the layout, specification, and site requirements. Build a repeatable approach that supports the whole programme.",
    "introLink": "Discover the build system",
    "benefit1": "One standard. Every building.",
    "benefit1Text": "Agree on the components, specification, and assembly approach before rollout. A shared standard makes a multi-building programme easier to coordinate.",
    "benefit2": "Different needs. One system.",
    "benefit2Text": "Housing, classrooms, shared facilities, or accommodation: define the spaces around the people who use them, with configurations reviewed for each project.",
    "benefit3": "Plan the whole programme.",
    "benefit3Text": "Bring capacity, site readiness, logistics, and delivery phases into the conversation early. Scale starts with a coordinated project brief.",
    "solutionLabel": "A DOCUMENTED REFERENCE DESIGN",
    "solutionTitle": "Explore a starting point.",
    "solutionAccent": "Type 36 is one example.",
    "solutionText": "See the layout, materials, and finishes of our documented 36 m² home. Your FAD project can have a different configuration; its design, specification, and price are confirmed through project review.",
    "type": "TYPE 36 / REFERENCE DESIGN",
    "concept": "Concept visual · Commercial deck",
    "area": "Floor area",
    "rooms": "Bedrooms",
    "panels": "Primary panels",
    "priceLabel": "PROJECT-SPECIFIC PROPOSAL",
    "priceNote": "Your design, specification, site conditions, logistics, and agreed scope shape the proposal. Talk to us about the scale and requirements of your programme.",
    "colorLabel": "SELECT YOUR FINISH",
    "olive": "Olive green",
    "brown": "Earthy brown",
    "yellow": "Golden yellow",
    "purple": "Royal purple",
    "download": "Download commercial deck",
    "specLink": "Discuss this reference design",
    "techLabel": "OUR BUILDING TECHNOLOGY",
    "techTitle": "One adaptable system.",
    "techAccent": "Many ways to build.",
    "techText": "High-density EPS, fiberglass reinforcement, and proprietary IQ structural resin form the FAD composite panel system. A consistent construction method for project-specific building configurations.",
    "techLayer1": "Fiberglass reinforcement",
    "techLayer2": "High-density EPS core",
    "techLayer3": "IQ structural resin bond",
    "techDiagram": "Illustrative panel cross-section",
    "techStat": "Composite panels",
    "techStatText": "A shared build system for a range of development needs",
    "tech1": "Prepare the foundation",
    "tech1Text": "A 50 cm stone/block base with steel anchors, subject to site engineering.",
    "tech2": "Assemble the structure",
    "tech2Text": "Connect pre-cut panels using the specified IQ resin bonding system.",
    "tech3": "Coat & finish",
    "tech3Text": "Apply the fiberglass matrix and finishes, then install UPVC doors and windows.",
    "techNote": "Assembly timing refers to the superstructure only. Overall delivery depends on foundation works, finishes, logistics, and site conditions.",
    "appLabel": "MODULAR SOLUTIONS FOR YOUR DEVELOPMENT",
    "appTitle": "Spaces for living.",
    "appAccent": "And everything around it.",
    "appText": "Choose the application that fits your programme. We’ll discuss the right configuration, specification, and scope for your project.",
    "app1": "Housing & residential",
    "app1Tag": "DEVELOPERS & GOVERNMENT",
    "app1Text": "From housing clusters to district-wide programmes, plan repeatable homes around your development brief.",
    "app2": "Education & learning",
    "app2Tag": "SCHOOLS & INSTITUTIONS",
    "app2Text": "Discuss classrooms, campus facilities, and learning spaces with layouts suited to the needs of your institution.",
    "app3": "Dormitories & accommodation",
    "app3Tag": "WORKFORCE & STUDENT HOUSING",
    "app3Text": "Plan accommodation for workers or students, with configurations reviewed for your capacity and site requirements.",
    "appCta": "Discuss this solution",
    "appNote": "Illustrative development concepts from the commercial deck; not completed project references.",
    "governmentLabel": "FOR PUBLIC-SECTOR & INSTITUTIONAL PARTNERS",
    "governmentTitle": "Big ambitions.",
    "governmentAccent": "A practical path forward.",
    "governmentText": "Planning a housing programme, educational facility, or accommodation project? Let’s align your use case, unit or capacity targets, site requirements, and procurement priorities.",
    "governmentCta": "Discuss a government project",
    "government1": "Programme-scale planning",
    "government2": "Site-specific scope review",
    "government3": "Technical documentation on request",
    "budgetLabel": "PLAN YOUR DEVELOPMENT",
    "budgetTitle": "Start with your scale.",
    "budgetAccent": "Shape the right solution.",
    "budgetText": "A housing cluster, a campus, or a workforce community: tell us how many repeatable spaces you are planning. We’ll review your configuration, site, and delivery requirements to prepare a tailored proposal.",
    "budgetUnits": "Planned buildings or repeatable units",
    "budgetResult": "YOUR PROGRAMME SCALE",
    "budgetRate": "planned units / buildings",
    "budgetNote": "Use this as a starting point for your brief. Capacity, floor area, technical specifications, scope, and pricing are defined for your project — there is no universal unit price.",
    "budgetCta": "Discuss my development",
    "faqLabel": "GET TO KNOW FAD",
    "faqTitle": "Your questions, answered.",
    "faq1": "Is FAD only for Type 36 homes?",
    "faq1Text": "No. FAD is a mass-scale development solution for residential housing, educational facilities, and accommodation. Type 36 is a documented reference design. Different uses, layouts, and configurations are reviewed and specified for each project.",
    "faq2": "How is the design decided?",
    "faq2Text": "Start with your intended use, location, required capacity or number of units, and programme priorities. The project conversation defines the configuration, technical requirements, and scope before confirming a proposal. The same design and specification can then be repeated where needed.",
    "faq3": "How are projects priced?",
    "faq3Text": "Every proposal is defined around your intended use, configuration, location, engineering, logistics, and agreed scope. Share your programme brief so we can discuss the right specification and commercial approach.",
    "faq4": "Can we review technical reports before procurement?",
    "faq4Text": "Yes — include your technical, testing, and procurement documentation needs in your enquiry. The team can discuss the supporting reports and their applicability to your site. Structural design and local approvals must be confirmed for each project.",
    "contactLabel": "LET’S BUILD WHAT’S NEXT",
    "contactTitle": "Tell us your vision.",
    "contactAccent": "We’ll explore the possibilities.",
    "contactText": "Housing, learning spaces, or accommodation — start with your use case, location, and scale. Our team can discuss the configuration and scope for your development.",
    "contactDirect": "Prefer a conversation?",
    "contactWhatsApp": "Talk to us on WhatsApp",
    "formTitle": "Let’s discuss your project",
    "formSubtitle": "Share your project needs with our team via WhatsApp.",
    "name": "Full name",
    "namePlaceholder": "Your full name",
    "org": "Organisation / institution",
    "orgPlaceholder": "Company or government agency",
    "email": "Work email",
    "phone": "Phone / WhatsApp",
    "location": "Project location",
    "locationPlaceholder": "City / regency, province",
    "sector": "Project type",
    "select": "Select an option",
    "sectorGov": "Government & public-sector programme",
    "sectorDev": "Residential development",
    "sectorEdu": "Educational facilities",
    "sectorCorp": "Worker / student housing",
    "sectorOther": "Other bulk project",
    "units": "Estimated number of units",
    "timeline": "Target timeline",
    "timeline1": "Within 3 months",
    "timeline2": "3–6 months",
    "timeline3": "6–12 months",
    "timeline4": "More than 12 months",
    "timeline5": "Early planning",
    "message": "Tell us more",
    "optional": "optional",
    "messagePlaceholder": "Site readiness, delivery goals, procurement or technical requirements…",
    "consent": "I agree to share these details with Fjäll via WhatsApp for this project enquiry.",
    "submit": "Prepare my project enquiry",
    "formNote": "Your details are not submitted here. Review your brief, then send it in WhatsApp to reach our team.",
    "required": "Required fields",
    "footerText": "Build smarter. Develop at scale.",
    "footerAbout": "A repeatable composite build system for residential, educational, and accommodation programmes.",
    "footerLinks": "EXPLORE",
    "footerContact": "CONNECT",
    "footerPrivacy": "Privacy & enquiries",
    "footerCopyright": "© {year} Fjäll Affordable Development. All rights reserved.",
    "footerMission": "ONE BUILDING SYSTEM. MANY POSSIBILITIES.",
    "reviewTitle": "Your project brief is ready.",
    "reviewText": "Review your details below. Continue to WhatsApp and send the message to deliver your enquiry to Fjäll.",
    "reviewSend": "Continue to WhatsApp",
    "reviewCopy": "Copy project brief",
    "copied": "Brief copied",
    "copyError": "Unable to copy. Select and copy the brief below.",
    "reviewEdit": "Back to editing",
    "reviewNote": "Opening WhatsApp does not send the message automatically.",
    "privacyTitle": "Your enquiry, your choice.",
    "privacyText": "This website does not submit your form details to a server or store them in your browser. The enquiry form prepares a message locally. If you choose to continue, your details are included in a WhatsApp link and handled by WhatsApp and Fjäll when you send it. Only your language preference is saved in this browser. The project calculator is indicative and does not collect personal information.",
    "privacyClose": "Understood",
    "briefHeading": "Fjäll Affordable Development — Project enquiry",
    "preferredLang": "Preferred language: English",
    "imageAlt": "FAD Type 36 housing concept in a landscaped setting",
    "panelAlt": "Diagram showing three layers of the composite panel system",
    "homeExterior": "Exterior",
    "homePlan": "Floor plan",
    "homeSpec": "Standard specification",
    "homeOverview": "REFERENCE HOME / TYPE 36",
    "specEyebrow": "A DEFINED STARTING POINT",
    "specTitle": "Type 36 reference specification.",
    "specDescription": "This specification applies to the deck’s Type 36 example. Other layouts and building programmes require their own project specification.",
    "specItem": "Component",
    "specValue": "Standard specification",
    "spec1": "Home configuration",
    "spec1Value": "36 m² · 2 bedrooms · living area · integrated wet core",
    "spec2": "Panel system",
    "spec2Value": "10 primary composite panels · 6 m × 2.4 m each",
    "spec3": "Wall composition",
    "spec3Value": "High-density EPS, fiberglass, IQ structural resin, and finishing layers",
    "spec4": "Foundation",
    "spec4Value": "50 cm stone / block base with steel anchors, subject to site engineering",
    "spec5": "Windows & doors",
    "spec5Value": "UPVC fixtures · 3 main windows + 1 upper ventilation window",
    "spec6": "Exterior finishes",
    "spec6Value": "Olive green / Earthy brown / Golden yellow / Royal purple",
    "scopeIncluded": "Type 36 reference inclusions",
    "scopeIncludedText": "Stone foundation & septic tank; FAD walls & roofing; UPVC doors, windows & exterior coating.",
    "scopeDeveloper": "Type 36 developer scope",
    "scopeDeveloperText": "Electrical installation & interior finishing. Final inclusions, local approvals, logistics, and taxes confirmed per project.",
    "planMaster": "Bedroom 01",
    "planSecond": "Bedroom 02",
    "planLiving": "Living area",
    "planWet": "Bath / kitchen",
    "planNote": "Illustrative zoning based on the commercial-deck room areas. Openings and arrangement are indicative, subject to architectural and site review.",
    "planCaption": "TYPE 36 / ILLUSTRATIVE ZONING",
    "specCta": "Discuss the standard specification",
    "finishNote": "Four finishes. One repeatable design.",
    "heroImageAlt": "Illustrative multi-building development concept from the Fjäll commercial deck",
    "budgetBrief": "Type 36 reference scenario",
    "capability1": "Residential",
    "capability1Text": "Homes & housing programmes",
    "capability2": "Education",
    "capability2Text": "Schools & campus facilities",
    "capability3": "Accommodation",
    "capability3Text": "Worker & student communities",
    "capability4": "Repeatable",
    "capability4Text": "A shared composite build system",
    "journeyLabel": "HOW YOUR PROJECT STARTS",
    "journeyTitle": "A clear process.",
    "journeyAccent": "From brief to build.",
    "journeyDescription": "Define the right solution before scaling it. Start a consultation with your project needs.",
    "journey1": "Share your project",
    "journey1Text": "Tell us the use, location, scale, and priorities for your development.",
    "journey2": "Align the configuration",
    "journey2Text": "Discuss layouts, capacity, and specifications that fit your programme.",
    "journey3": "Review site & scope",
    "journey3Text": "Confirm technical needs, inclusions, procurement, and commercial requirements.",
    "journey4": "Plan delivery",
    "journey4Text": "Align the proposed build approach, phasing, and delivery responsibilities.",
    "journeyCta": "Start a consultation",
    "preloaderLabel": "ONE SYSTEM. MANY POSSIBILITIES.",
    "preloaderSkip": "Enter website",
    "filmLabel": "THE FAD SYSTEM IN MOTION",
    "filmTitle": "From one module to a whole programme.",
    "filmText": "Watch the FAD concept: repeatable components, coordinated buildings, and development at scale. An illustrative animation of the system, rather than completed project footage.",
    "offerLabel": "FROM BRIEF TO ROLLOUT",
    "offerTitle": "A development partner.",
    "offerAccent": "A repeatable way forward.",
    "offerText": "Inspired by the clarity of modular construction: start with the application, coordinate the build system, and plan the programme. Your FAD scope is agreed around your project.",
    "offer1": "Define your spaces",
    "offer1Text": "Align intended use, layouts, capacity, and a common specification for your development.",
    "offer2": "Coordinate the build",
    "offer2Text": "Review the composite system, foundation requirements, site works, and responsibilities before delivery.",
    "offer3": "Plan your rollout",
    "offer3Text": "Discuss quantities, delivery phases, site readiness, and logistics for a coordinated programme."
  },
  "id": {
    "skip": "Langsung ke konten",
    "navSolution": "Solusi",
    "navTech": "Cara kami membangun",
    "navProjects": "Penerapan",
    "navContact": "Konsultasikan proyek",
    "menu": "Buka menu",
    "close": "Tutup",
    "brandSub": "AFFORDABLE DEVELOPMENT",
    "group": "BAGIAN DARI GRUP",
    "heroEyebrow": "FJÄLL AFFORDABLE DEVELOPMENT",
    "heroTitle": "Bangun lebih cerdas.",
    "heroAccent": "Kembangkan skalanya.",
    "heroDescription": "Pengembangan skala besar dengan sistem yang dapat direplikasi. Dari kawasan hunian hingga ruang belajar dan akomodasi tenaga kerja, selaraskan desain dan spesifikasi — lalu rencanakan pengembangan secara terarah.",
    "heroCta": "Mari diskusikan proyek Anda",
    "heroSecondary": "Jelajahi solusi kami",
    "heroTag": "Untuk pengembang, program pemerintah & institusi",
    "heroCaption": "ILUSTRASI KONSEP PENGEMBANGAN",
    "heroCardTitle": "Satu sistem bangun. Banyak kemungkinan.",
    "heroCardText": "Perumahan · Pendidikan · Akomodasi",
    "metric1": "Luas hunian standar",
    "metric2": "Perakitan struktur atas¹",
    "metric3": "Berat struktur ringan¹",
    "introLabel": "KEUNGGULAN FAD",
    "introTitle": "Cara membangun lebih cerdas.",
    "introAccent": "Sistem untuk skala besar.",
    "introText": "Pikirkan lebih dari satu bangunan. FAD menghadirkan sistem bangunan komposit terstandar untuk pengembangan dengan banyak unit, fungsi, dan tahap pelaksanaan. Mulai dari kebutuhan Anda. Tetapkan tata ruang, spesifikasi, dan kondisi lokasi. Susun pendekatan yang dapat direplikasi untuk seluruh program.",
    "introLink": "Kenali sistem bangun kami",
    "benefit1": "Satu standar. Setiap bangunan.",
    "benefit1Text": "Sepakati komponen, spesifikasi, dan metode perakitan sebelum pelaksanaan. Standar bersama memudahkan koordinasi program dengan banyak bangunan.",
    "benefit2": "Beragam kebutuhan. Satu sistem.",
    "benefit2Text": "Hunian, ruang kelas, fasilitas bersama, atau akomodasi: tentukan ruang berdasarkan kebutuhan penggunanya, dengan konfigurasi yang dikaji untuk setiap proyek.",
    "benefit3": "Rencanakan seluruh program.",
    "benefit3Text": "Bahas kapasitas, kesiapan lokasi, logistik, dan tahap pelaksanaan sejak awal. Pengembangan skala besar dimulai dari kebutuhan proyek yang terkoordinasi.",
    "solutionLabel": "CONTOH DESAIN YANG TERDOKUMENTASI",
    "solutionTitle": "Jelajahi titik awal.",
    "solutionAccent": "Tipe 36 adalah salah satu contoh.",
    "solutionText": "Lihat tata letak, material, dan warna hunian 36 m² yang terdokumentasi. Proyek FAD Anda dapat memiliki konfigurasi berbeda; desain, spesifikasi, dan harga dikonfirmasi melalui kajian proyek.",
    "type": "TIPE 36 / DESAIN REFERENSI",
    "concept": "Visual konsep · Materi komersial",
    "area": "Luas lantai",
    "rooms": "Kamar tidur",
    "panels": "Panel utama",
    "priceLabel": "PROPOSAL KHUSUS PROYEK",
    "priceNote": "Desain, spesifikasi, kondisi lokasi, logistik, dan lingkup yang disepakati menjadi dasar proposal. Diskusikan skala dan kebutuhan program Anda.",
    "colorLabel": "PILIH WARNA ANDA",
    "olive": "Hijau zaitun",
    "brown": "Cokelat bumi",
    "yellow": "Kuning keemasan",
    "purple": "Ungu royal",
    "download": "Unduh materi komersial",
    "specLink": "Diskusikan desain referensi ini",
    "techLabel": "TEKNOLOGI BANGUNAN KAMI",
    "techTitle": "Satu sistem adaptif.",
    "techAccent": "Banyak cara membangun.",
    "techText": "EPS berkepadatan tinggi, penguat fiberglass, dan resin struktural IQ membentuk sistem panel komposit FAD. Metode konstruksi konsisten untuk konfigurasi bangunan sesuai proyek.",
    "techLayer1": "Penguat fiberglass",
    "techLayer2": "Inti EPS berkepadatan tinggi",
    "techLayer3": "Ikatan resin struktural IQ",
    "techDiagram": "Ilustrasi penampang panel",
    "techStat": "Panel komposit",
    "techStatText": "Sistem bangun bersama untuk berbagai kebutuhan pengembangan",
    "tech1": "Siapkan fondasi",
    "tech1Text": "Dasar batu/blok 50 cm dengan jangkar baja, sesuai kajian teknik lokasi.",
    "tech2": "Rakit struktur",
    "tech2Text": "Hubungkan panel yang telah dipotong dengan sistem ikatan resin IQ yang ditentukan.",
    "tech3": "Lapisi & selesaikan",
    "tech3Text": "Aplikasikan matriks fiberglass dan lapisan akhir, lalu pasang pintu dan jendela UPVC.",
    "techNote": "Waktu perakitan hanya untuk struktur atas. Penyelesaian keseluruhan bergantung pada fondasi, finishing, logistik, dan kondisi lokasi.",
    "appLabel": "SOLUSI MODULAR UNTUK PENGEMBANGAN ANDA",
    "appTitle": "Ruang untuk tinggal.",
    "appAccent": "Dan kebutuhan di sekitarnya.",
    "appText": "Pilih penerapan yang sesuai program Anda. Mari diskusikan konfigurasi, spesifikasi, dan lingkup yang tepat untuk proyek Anda.",
    "app1": "Perumahan & hunian",
    "app1Tag": "PENGEMBANG & PEMERINTAH",
    "app1Text": "Dari klaster hunian hingga program satu daerah, rencanakan rumah yang dapat direplikasi sesuai ringkasan pengembangan Anda.",
    "app2": "Pendidikan & pembelajaran",
    "app2Tag": "SEKOLAH & INSTITUSI",
    "app2Text": "Diskusikan ruang kelas, fasilitas kampus, dan ruang belajar dengan tata letak sesuai kebutuhan institusi Anda.",
    "app3": "Asrama & akomodasi",
    "app3Tag": "HUNIAN PEKERJA & MAHASISWA",
    "app3Text": "Rencanakan akomodasi pekerja atau mahasiswa, dengan konfigurasi yang dikaji sesuai kapasitas dan kebutuhan lokasi.",
    "appCta": "Diskusikan solusi ini",
    "appNote": "Ilustrasi konsep pengembangan dari materi komersial; bukan referensi proyek yang telah selesai.",
    "governmentLabel": "UNTUK MITRA SEKTOR PUBLIK & INSTITUSI",
    "governmentTitle": "Ambisi besar.",
    "governmentAccent": "Langkah nyata ke depan.",
    "governmentText": "Merencanakan program hunian, fasilitas pendidikan, atau proyek akomodasi? Mari selaraskan penggunaan, target unit atau kapasitas, kebutuhan lokasi, dan prioritas pengadaan Anda.",
    "governmentCta": "Diskusikan proyek pemerintah",
    "government1": "Perencanaan skala program",
    "government2": "Kajian lingkup sesuai lokasi",
    "government3": "Dokumentasi teknis sesuai permintaan",
    "budgetLabel": "RENCANAKAN PENGEMBANGAN ANDA",
    "budgetTitle": "Mulai dari skalanya.",
    "budgetAccent": "Tentukan solusi yang tepat.",
    "budgetText": "Kawasan hunian, kampus, atau komunitas pekerja: sampaikan jumlah bangunan atau unit berulang yang Anda rencanakan. Kami akan mengkaji konfigurasi, lokasi, dan kebutuhan pelaksanaan untuk menyusun proposal khusus.",
    "budgetUnits": "Jumlah bangunan atau unit yang direncanakan",
    "budgetResult": "SKALA PROGRAM ANDA",
    "budgetRate": "unit / bangunan yang direncanakan",
    "budgetNote": "Gunakan sebagai titik awal kebutuhan proyek. Kapasitas, luas, spesifikasi teknis, lingkup, dan harga ditentukan sesuai proyek — tidak ada harga unit universal.",
    "budgetCta": "Diskusikan pengembangan saya",
    "faqLabel": "KENALI FAD LEBIH DEKAT",
    "faqTitle": "Pertanyaan Anda, terjawab.",
    "faq1": "Apakah FAD hanya untuk hunian Tipe 36?",
    "faq1Text": "Tidak. FAD adalah solusi pengembangan skala massal untuk perumahan, fasilitas pendidikan, dan akomodasi. Tipe 36 adalah desain referensi yang terdokumentasi. Penggunaan, tata letak, dan konfigurasi berbeda dikaji serta ditentukan untuk setiap proyek.",
    "faq2": "Bagaimana desain ditentukan?",
    "faq2Text": "Mulai dari penggunaan, lokasi, kapasitas atau jumlah unit yang dibutuhkan, dan prioritas program. Diskusi proyek menentukan konfigurasi, kebutuhan teknis, dan lingkup sebelum proposal dikonfirmasi. Desain dan spesifikasi yang sama dapat direplikasi sesuai kebutuhan.",
    "faq3": "Bagaimana harga proyek ditentukan?",
    "faq3Text": "Setiap proposal disusun berdasarkan fungsi, konfigurasi, lokasi, rekayasa teknik, logistik, dan lingkup yang disepakati. Sampaikan kebutuhan program agar kami dapat membahas spesifikasi dan pendekatan komersial yang sesuai.",
    "faq4": "Bisakah kami meninjau laporan teknis sebelum pengadaan?",
    "faq4Text": "Ya — cantumkan kebutuhan dokumentasi teknis, pengujian, dan pengadaan dalam pertanyaan Anda. Tim dapat mendiskusikan laporan pendukung serta kesesuaiannya dengan lokasi. Desain struktural dan izin setempat harus dikonfirmasi untuk setiap proyek.",
    "contactLabel": "MARI MEMBANGUN MASA DEPAN",
    "contactTitle": "Ceritakan visi Anda.",
    "contactAccent": "Mari jelajahi kemungkinannya.",
    "contactText": "Hunian, ruang belajar, atau akomodasi — mulai dari penggunaan, lokasi, dan skala. Tim kami dapat mendiskusikan konfigurasi dan lingkup pengembangan Anda.",
    "contactDirect": "Ingin berdiskusi langsung?",
    "contactWhatsApp": "Hubungi kami di WhatsApp",
    "formTitle": "Mari diskusikan proyek Anda",
    "formSubtitle": "Bagikan kebutuhan proyek kepada tim kami melalui WhatsApp.",
    "name": "Nama lengkap",
    "namePlaceholder": "Nama lengkap Anda",
    "org": "Organisasi / institusi",
    "orgPlaceholder": "Perusahaan atau instansi pemerintah",
    "email": "Email kerja",
    "phone": "Telepon / WhatsApp",
    "location": "Lokasi proyek",
    "locationPlaceholder": "Kota / kabupaten, provinsi",
    "sector": "Jenis proyek",
    "select": "Pilih opsi",
    "sectorGov": "Program pemerintah & sektor publik",
    "sectorDev": "Pengembangan perumahan",
    "sectorEdu": "Fasilitas pendidikan",
    "sectorCorp": "Hunian pekerja / mahasiswa",
    "sectorOther": "Proyek massal lainnya",
    "units": "Estimasi jumlah unit",
    "timeline": "Target waktu",
    "timeline1": "Dalam 3 bulan",
    "timeline2": "3–6 bulan",
    "timeline3": "6–12 bulan",
    "timeline4": "Lebih dari 12 bulan",
    "timeline5": "Perencanaan awal",
    "message": "Informasi tambahan",
    "optional": "opsional",
    "messagePlaceholder": "Kesiapan lokasi, target pelaksanaan, persyaratan pengadaan atau teknis…",
    "consent": "Saya setuju membagikan informasi ini kepada Fjäll melalui WhatsApp untuk pertanyaan proyek ini.",
    "submit": "Siapkan pertanyaan proyek",
    "formNote": "Informasi Anda belum dikirim di sini. Tinjau ringkasan, lalu kirim di WhatsApp untuk menghubungi tim kami.",
    "required": "Kolom wajib",
    "footerText": "Bangun cerdas. Kembangkan skala.",
    "footerAbout": "Sistem bangunan komposit yang dapat direplikasi untuk program hunian, pendidikan, dan akomodasi.",
    "footerLinks": "JELAJAHI",
    "footerContact": "HUBUNGI",
    "footerPrivacy": "Privasi & pertanyaan",
    "footerCopyright": "© {year} Fjäll Affordable Development. Hak cipta dilindungi.",
    "footerMission": "SATU SISTEM BANGUN. BANYAK KEMUNGKINAN.",
    "reviewTitle": "Ringkasan proyek Anda siap.",
    "reviewText": "Tinjau informasi di bawah. Lanjutkan ke WhatsApp dan kirim pesan untuk menyampaikan pertanyaan Anda kepada Fjäll.",
    "reviewSend": "Lanjutkan ke WhatsApp",
    "reviewCopy": "Salin ringkasan proyek",
    "copied": "Ringkasan disalin",
    "copyError": "Tidak dapat menyalin. Pilih dan salin ringkasan di bawah.",
    "reviewEdit": "Kembali mengedit",
    "reviewNote": "Membuka WhatsApp tidak mengirim pesan secara otomatis.",
    "privacyTitle": "Pertanyaan Anda, pilihan Anda.",
    "privacyText": "Situs ini tidak mengirim informasi formulir ke server atau menyimpannya di browser. Formulir menyiapkan pesan secara lokal. Jika Anda melanjutkan, informasi dimasukkan ke tautan WhatsApp dan dikelola oleh WhatsApp serta Fjäll saat dikirim. Hanya preferensi bahasa yang disimpan di browser ini. Kalkulator proyek bersifat indikatif dan tidak mengumpulkan informasi pribadi.",
    "privacyClose": "Mengerti",
    "briefHeading": "Fjäll Affordable Development — Pertanyaan proyek",
    "preferredLang": "Bahasa pilihan: Bahasa Indonesia",
    "imageAlt": "Konsep hunian FAD Tipe 36 dengan taman",
    "panelAlt": "Diagram tiga lapisan sistem panel komposit",
    "homeExterior": "Eksterior",
    "homePlan": "Denah",
    "homeSpec": "Spesifikasi standar",
    "homeOverview": "HUNIAN REFERENSI / TIPE 36",
    "specEyebrow": "TITIK AWAL YANG TERDEFINISI",
    "specTitle": "Spesifikasi referensi Tipe 36.",
    "specDescription": "Spesifikasi ini berlaku untuk contoh Tipe 36 dalam materi komersial. Tata letak dan program bangunan lain memerlukan spesifikasi proyek tersendiri.",
    "specItem": "Komponen",
    "specValue": "Spesifikasi standar",
    "spec1": "Konfigurasi hunian",
    "spec1Value": "36 m² · 2 kamar tidur · ruang keluarga · blok kamar mandi / dapur",
    "spec2": "Sistem panel",
    "spec2Value": "10 panel komposit utama · masing-masing 6 m × 2,4 m",
    "spec3": "Komposisi dinding",
    "spec3Value": "EPS berkepadatan tinggi, fiberglass, resin struktural IQ, dan lapisan akhir",
    "spec4": "Fondasi",
    "spec4Value": "Dasar batu / blok 50 cm dengan jangkar baja, sesuai kajian teknik lokasi",
    "spec5": "Jendela & pintu",
    "spec5Value": "Perlengkapan UPVC · 3 jendela utama + 1 jendela ventilasi atas",
    "spec6": "Warna eksterior",
    "spec6Value": "Hijau zaitun / Cokelat bumi / Kuning keemasan / Ungu royal",
    "scopeIncluded": "Cakupan referensi Tipe 36",
    "scopeIncludedText": "Fondasi batu & tangki septik; dinding & atap FAD; pintu, jendela UPVC & lapisan eksterior.",
    "scopeDeveloper": "Lingkup pengembang Tipe 36",
    "scopeDeveloperText": "Instalasi listrik & finishing interior. Cakupan akhir, perizinan setempat, logistik, dan pajak dikonfirmasi per proyek.",
    "planMaster": "Kamar tidur 01",
    "planSecond": "Kamar tidur 02",
    "planLiving": "Ruang keluarga",
    "planWet": "Kamar mandi / dapur",
    "planNote": "Ilustrasi pembagian ruang berdasarkan luas ruang dalam materi komersial. Bukaan dan susunan bersifat indikatif, sesuai kajian arsitektur dan lokasi.",
    "planCaption": "TIPE 36 / ILUSTRASI PEMBAGIAN RUANG",
    "specCta": "Diskusikan spesifikasi standar",
    "finishNote": "Empat warna. Satu desain yang dapat direplikasi.",
    "heroImageAlt": "Ilustrasi konsep pengembangan beberapa bangunan dari materi komersial Fjäll",
    "budgetBrief": "Skenario referensi Tipe 36",
    "capability1": "Perumahan",
    "capability1Text": "Hunian & program perumahan",
    "capability2": "Pendidikan",
    "capability2Text": "Sekolah & fasilitas kampus",
    "capability3": "Akomodasi",
    "capability3Text": "Komunitas pekerja & mahasiswa",
    "capability4": "Replikasi",
    "capability4Text": "Sistem bangun panel komposit",
    "journeyLabel": "LANGKAH AWAL PROYEK ANDA",
    "journeyTitle": "Proses yang jelas.",
    "journeyAccent": "Dari kebutuhan ke pembangunan.",
    "journeyDescription": "Tentukan solusi yang tepat sebelum memperbesar skala. Mulai konsultasi dengan kebutuhan proyek Anda.",
    "journey1": "Sampaikan proyek Anda",
    "journey1Text": "Ceritakan penggunaan, lokasi, skala, dan prioritas pengembangan Anda.",
    "journey2": "Selaraskan konfigurasi",
    "journey2Text": "Diskusikan tata letak, kapasitas, dan spesifikasi yang sesuai program Anda.",
    "journey3": "Kaji lokasi & lingkup",
    "journey3Text": "Konfirmasikan kebutuhan teknis, cakupan, pengadaan, dan persyaratan komersial.",
    "journey4": "Rencanakan pelaksanaan",
    "journey4Text": "Selaraskan pendekatan bangun, tahapan, dan tanggung jawab pelaksanaan yang diusulkan.",
    "journeyCta": "Mulai konsultasi",
    "preloaderLabel": "SATU SISTEM. BERAGAM KEMUNGKINAN.",
    "preloaderSkip": "Masuk ke situs",
    "filmLabel": "SISTEM FAD DALAM GERAK",
    "filmTitle": "Dari satu modul ke seluruh program.",
    "filmText": "Lihat konsep FAD: komponen berulang, bangunan terkoordinasi, dan pengembangan skala besar. Animasi ilustratif sistem, bukan dokumentasi proyek yang telah selesai.",
    "offerLabel": "DARI KEBUTUHAN HINGGA PELAKSANAAN",
    "offerTitle": "Mitra pengembangan.",
    "offerAccent": "Pendekatan yang dapat direplikasi.",
    "offerText": "Mengadopsi kejelasan konstruksi modular: mulai dari fungsi, koordinasikan sistem bangunan, lalu rencanakan program. Lingkup FAD disepakati sesuai proyek Anda.",
    "offer1": "Tentukan kebutuhan ruang",
    "offer1Text": "Selaraskan fungsi, tata ruang, kapasitas, dan spesifikasi bersama untuk pengembangan Anda.",
    "offer2": "Koordinasikan pembangunan",
    "offer2Text": "Kaji sistem komposit, kebutuhan fondasi, pekerjaan lokasi, dan tanggung jawab sebelum pelaksanaan.",
    "offer3": "Rencanakan pelaksanaan",
    "offer3Text": "Diskusikan jumlah, tahap pelaksanaan, kesiapan lokasi, dan logistik untuk program yang terkoordinasi."
  }
};
