export const content = {
  "en": {
    "skip": "Skip to content",
    "navSolution": "Solutions",
    "navTech": "Government projects",
    "navProjects": "Applications",
    "navContact": "Consult your project",
    "menu": "Open menu",
    "close": "Close",
    "brandSub": "AFFORDABLE DEVELOPMENT",
    "group": "PART OF THE GROUP",
    "heroEyebrow": "FJÄLL AFFORDABLE DEVELOPMENT",
    "heroTitle": "Build smarter.",
    "heroAccent": "Scale further.",
    "heroDescription": "Mass-scale development, built on a repeatable system. From residential communities to worker accommodation, schools, and healthcare facilities, align the design and specification — then plan a coordinated rollout.",
    "heroCta": "Let’s talk about your project",
    "heroSecondary": "Explore our solutions",
    "heroTag": "For developers, government programmes & institutions",
    "heroCaption": "ILLUSTRATIVE DEVELOPMENT CONCEPT",
    "heroCardTitle": "One building system. Many possibilities.",
    "heroCardText": "Housing · Education · Accommodation",
    "metric1": "Standard home footprint",
    "metric2": "Superstructure assembly¹",
    "metric3": "Lightweight structure¹",
    "introLabel": "THE FAD ADVANTAGE",
    "introTitle": "A smarter way to build.",
    "introAccent": "A system designed to scale.",
    "introText": "Think beyond a single building. FAD brings a standardised composite build system to developments with multiple units, uses, and delivery phases. Start with your brief. Define the layout, specification, and site requirements. Build a repeatable approach that supports the whole programme.",
    "introLink": "Explore government programmes",
    "benefit1": "One standard. Every building.",
    "benefit1Text": "Agree on the components, specification, and assembly approach before rollout. A shared standard makes a multi-building programme easier to coordinate.",
    "benefit2": "Different needs. One system.",
    "benefit2Text": "Housing, classrooms, shared facilities, or accommodation: define the spaces around the people who use them, with configurations reviewed for each project.",
    "benefit3": "Plan the whole programme.",
    "benefit3Text": "Bring capacity, site readiness, logistics, and delivery phases into the conversation early. Scale starts with a coordinated project brief.",
    "solutionLabel": "A DOCUMENTED REFERENCE DESIGN",
    "solutionTitle": "Explore a starting point.",
    "solutionAccent": "Type 36 is one example.",
    "solutionText": "See the layout, materials, and finishes of our documented 36 m² home. Your FAD project can have a different configuration; its design, specification, and price are confirmed through project review.",
    "type": "TYPE 36 / REFERENCE DESIGN",
    "concept": "Illustrative architectural concept",
    "area": "Floor area",
    "rooms": "Bedrooms",
    "panels": "Primary panels",
    "priceLabel": "PROJECT-SPECIFIC PROPOSAL",
    "priceNote": "Your design, specification, site conditions, logistics, and agreed scope shape the proposal. Talk to us about the scale and requirements of your programme.",
    "colorLabel": "SELECT YOUR FINISH",
    "olive": "Olive green",
    "brown": "Earthy brown",
    "yellow": "Golden yellow",
    "purple": "Royal purple",
    "download": "Download commercial deck",
    "specLink": "Discuss this reference design",
    "techLabel": "OUR BUILDING TECHNOLOGY",
    "techTitle": "One adaptable system.",
    "techAccent": "Many ways to build.",
    "techText": "High-density EPS, fiberglass reinforcement, and proprietary IQ structural resin form the FAD composite panel system. A consistent construction method for project-specific building configurations.",
    "techLayer1": "Fiberglass reinforcement",
    "techLayer2": "High-density EPS core",
    "techLayer3": "IQ structural resin bond",
    "techDiagram": "Illustrative panel cross-section",
    "techStat": "Composite panels",
    "techStatText": "A shared build system for a range of development needs",
    "tech1": "Prepare the foundation",
    "tech1Text": "A 50 cm stone/block base with steel anchors, subject to site engineering.",
    "tech2": "Assemble the structure",
    "tech2Text": "Connect pre-cut panels using the specified IQ resin bonding system.",
    "tech3": "Coat & finish",
    "tech3Text": "Apply the fiberglass matrix and finishes, then install UPVC doors and windows.",
    "techNote": "Assembly timing refers to the superstructure only. Overall delivery depends on foundation works, finishes, logistics, and site conditions.",
    "appLabel": "MODULAR SOLUTIONS FOR YOUR DEVELOPMENT",
    "appTitle": "Spaces for living.",
    "appAccent": "And everything around it.",
    "appText": "Choose the application that fits your programme. We’ll discuss the right configuration, specification, and scope for your project.",
    "app1": "Housing & residential",
    "app1Tag": "DEVELOPERS & GOVERNMENT",
    "app1Text": "From housing clusters to district-wide programmes, plan repeatable homes around your development brief.",
    "app2": "Education & learning",
    "app2Tag": "SCHOOLS & INSTITUTIONS",
    "app2Text": "Discuss classrooms, campus facilities, and learning spaces with layouts suited to the needs of your institution.",
    "app3": "Dormitories & accommodation",
    "app3Tag": "WORKFORCE & STUDENT HOUSING",
    "app3Text": "Plan accommodation for workers or students, with configurations reviewed for your capacity and site requirements.",
    "appCta": "Discuss this solution",
    "appNote": "Illustrative architectural concepts, including AI-enhanced visuals; not completed project references. Final design and scope are project-specific.",
    "governmentLabel": "PUBLIC-SECTOR DEVELOPMENT",
    "governmentTitle": "Build public value.",
    "governmentAccent": "Deliver at scale.",
    "governmentText": "Turn a programme brief into a coordinated development conversation. FAD works around your public-service priorities, locations, target capacity, and procurement pathway — with a project-specific design, specification, and proposal.",
    "governmentCta": "Start a government project brief",
    "government1": "Programme-scale planning",
    "government2": "Site-specific scope review",
    "government3": "Technical documentation on request",
    "budgetLabel": "PLAN YOUR DEVELOPMENT",
    "budgetTitle": "Start with your scale.",
    "budgetAccent": "Shape the right solution.",
    "budgetText": "A housing cluster, a campus, or a workforce community: tell us how many repeatable spaces you are planning. We’ll review your configuration, site, and delivery requirements to prepare a tailored proposal.",
    "budgetUnits": "Planned buildings or repeatable units",
    "budgetResult": "YOUR PROGRAMME SCALE",
    "budgetRate": "planned units / buildings",
    "budgetNote": "Use this as a starting point for your brief. Capacity, floor area, technical specifications, scope, and pricing are defined for your project — there is no universal unit price.",
    "budgetCta": "Discuss my development",
    "faqLabel": "GET TO KNOW FAD",
    "faqTitle": "Your questions, answered.",
    "faq1": "Is FAD only for Type 36 homes?",
    "faq1Text": "No. FAD is a mass-scale development solution for residential housing, worker accommodation, and educational facilities, with healthcare campus uses reviewed around specialist requirements. Type 36 is a documented reference design. Different uses, layouts, and configurations are reviewed and specified for each project.",
    "faq2": "How is the design decided?",
    "faq2Text": "Start with your intended use, location, required capacity or number of units, and programme priorities. The project conversation defines the configuration, technical requirements, and scope before confirming a proposal. The same design and specification can then be repeated where needed.",
    "faq3": "How are projects priced?",
    "faq3Text": "Every proposal is defined around your intended use, configuration, location, engineering, logistics, and agreed scope. Share your programme brief so we can discuss the right specification and commercial approach.",
    "faq4": "Can we review technical reports before procurement?",
    "faq4Text": "Yes — include your technical, testing, and procurement documentation needs in your enquiry. The team can discuss the supporting reports and their applicability to your site. Structural design and local approvals must be confirmed for each project.",
    "contactLabel": "LET’S BUILD WHAT’S NEXT",
    "contactTitle": "Tell us your vision.",
    "contactAccent": "We’ll explore the possibilities.",
    "contactText": "Housing, learning spaces, or accommodation — start with your use case, location, and scale. Our team can discuss the configuration and scope for your development.",
    "contactDirect": "Prefer a conversation?",
    "contactWhatsApp": "Talk to us on WhatsApp",
    "formTitle": "Let’s discuss your project",
    "formSubtitle": "Share your project needs with our team via WhatsApp.",
    "name": "Full name",
    "namePlaceholder": "Your full name",
    "org": "Organisation / institution",
    "orgPlaceholder": "Company or government agency",
    "email": "Work email",
    "phone": "Phone / WhatsApp",
    "location": "Project location",
    "locationPlaceholder": "City / regency, province",
    "sector": "Project type",
    "select": "Select an option",
    "sectorGov": "Government & public-sector programme",
    "sectorDev": "Residential development",
    "sectorEdu": "Educational facilities",
    "sectorCorp": "Worker / student housing",
    "sectorOther": "Other bulk project",
    "units": "Estimated number of units",
    "timeline": "Target timeline",
    "timeline1": "Within 3 months",
    "timeline2": "3–6 months",
    "timeline3": "6–12 months",
    "timeline4": "More than 12 months",
    "timeline5": "Early planning",
    "message": "Tell us more",
    "optional": "optional",
    "messagePlaceholder": "Site readiness, delivery goals, procurement or technical requirements…",
    "consent": "I agree to share these details with Fjäll via WhatsApp for this project enquiry.",
    "submit": "Prepare my project enquiry",
    "formNote": "Your details are not submitted here. Review your brief, then send it in WhatsApp to reach our team.",
    "required": "Required fields",
    "footerText": "Build smarter. Develop at scale.",
    "footerAbout": "A repeatable composite build system for residential, educational, and accommodation programmes.",
    "footerLinks": "EXPLORE",
    "footerContact": "CONNECT",
    "footerPrivacy": "Privacy & enquiries",
    "footerCopyright": "© {year} Fjäll Affordable Development. All rights reserved.",
    "footerMission": "ONE BUILDING SYSTEM. MANY POSSIBILITIES.",
    "reviewTitle": "Your project brief is ready.",
    "reviewText": "Review your details below. Continue to WhatsApp and send the message to deliver your enquiry to Fjäll.",
    "reviewSend": "Continue to WhatsApp",
    "reviewCopy": "Copy project brief",
    "copied": "Brief copied",
    "copyError": "Unable to copy. Select and copy the brief below.",
    "reviewEdit": "Back to editing",
    "reviewNote": "Opening WhatsApp does not send the message automatically.",
    "privacyTitle": "Your enquiry, your choice.",
    "privacyText": "This website does not submit your form details to a server or store them in your browser. The enquiry form prepares a message locally. If you choose to continue, your details are included in a WhatsApp link and handled by WhatsApp and Fjäll when you send it. Your language preference is saved locally. The programme planner does not collect personal information.",
    "privacyClose": "Understood",
    "briefHeading": "Fjäll Affordable Development — Project enquiry",
    "preferredLang": "Preferred language: English",
    "imageAlt": "FAD Type 36 housing concept in a landscaped setting",
    "panelAlt": "Diagram showing three layers of the composite panel system",
    "homeExterior": "Exterior",
    "homePlan": "Floor plan",
    "homeSpec": "Standard specification",
    "homeOverview": "REFERENCE HOME / TYPE 36",
    "specEyebrow": "A DEFINED STARTING POINT",
    "specTitle": "Type 36 reference specification.",
    "specDescription": "This specification applies to the deck’s Type 36 example. Other layouts and building programmes require their own project specification.",
    "specItem": "Component",
    "specValue": "Standard specification",
    "spec1": "Home configuration",
    "spec1Value": "36 m² · 2 bedrooms · living area · integrated wet core",
    "spec2": "Panel system",
    "spec2Value": "10 primary composite panels · 6 m × 2.4 m each",
    "spec3": "Wall composition",
    "spec3Value": "High-density EPS, fiberglass, IQ structural resin, and finishing layers",
    "spec4": "Foundation",
    "spec4Value": "50 cm stone / block base with steel anchors, subject to site engineering",
    "spec5": "Windows & doors",
    "spec5Value": "UPVC fixtures · 3 main windows + 1 upper ventilation window",
    "spec6": "Exterior finishes",
    "spec6Value": "Olive green / Earthy brown / Golden yellow / Royal purple",
    "scopeIncluded": "Type 36 reference inclusions",
    "scopeIncludedText": "Stone foundation & septic tank; FAD walls & roofing; UPVC doors, windows & exterior coating.",
    "scopeDeveloper": "Type 36 developer scope",
    "scopeDeveloperText": "Electrical installation & interior finishing. Final inclusions, local approvals, logistics, and taxes confirmed per project.",
    "planMaster": "Bedroom 01",
    "planSecond": "Bedroom 02",
    "planLiving": "Living area",
    "planWet": "Bath / kitchen",
    "planNote": "Illustrative zoning based on the commercial-deck room areas. Openings and arrangement are indicative, subject to architectural and site review.",
    "planCaption": "TYPE 36 / ILLUSTRATIVE ZONING",
    "specCta": "Discuss the standard specification",
    "finishNote": "Four finishes. One repeatable design.",
    "heroImageAlt": "Illustrative multi-building development concept from the Fjäll commercial deck",
    "budgetBrief": "Type 36 reference scenario",
    "capability1": "Residential",
    "capability1Text": "Homes & housing programmes",
    "capability2": "Education",
    "capability2Text": "Schools & campus facilities",
    "capability3": "Accommodation",
    "capability3Text": "Worker & student communities",
    "capability4": "Repeatable",
    "capability4Text": "A shared composite build system",
    "journeyLabel": "HOW YOUR PROJECT STARTS",
    "journeyTitle": "A clear process.",
    "journeyAccent": "From brief to build.",
    "journeyDescription": "Define the right solution before scaling it. Start a consultation with your project needs.",
    "journey1": "Share your project",
    "journey1Text": "Tell us the use, location, scale, and priorities for your development.",
    "journey2": "Align the configuration",
    "journey2Text": "Discuss layouts, capacity, and specifications that fit your programme.",
    "journey3": "Review site & scope",
    "journey3Text": "Confirm technical needs, inclusions, procurement, and commercial requirements.",
    "journey4": "Plan delivery",
    "journey4Text": "Align the proposed build approach, phasing, and delivery responsibilities.",
    "journeyCta": "Start a consultation",
    "preloaderLabel": "ONE SYSTEM. MANY POSSIBILITIES.",
    "preloaderSkip": "Enter website",
    "filmLabel": "THE FAD SYSTEM IN MOTION",
    "filmTitle": "From one module to a whole programme.",
    "filmText": "Realistic architectural concept imagery brings FAD’s applications into view: homes, worker accommodation, schools, and healthcare facilities. These are illustrative concepts, not completed-project footage.",
    "offerLabel": "FROM BRIEF TO ROLLOUT",
    "offerTitle": "A development partner.",
    "offerAccent": "A repeatable way forward.",
    "offerText": "Inspired by the clarity of modular construction: start with the application, coordinate the build system, and plan the programme. Your FAD scope is agreed around your project.",
    "offer1": "Define your spaces",
    "offer1Text": "Align intended use, layouts, capacity, and a common specification for your development.",
    "offer2": "Coordinate the build",
    "offer2Text": "Review the composite system, foundation requirements, site works, and responsibilities before delivery.",
    "offer3": "Plan your rollout",
    "offer3Text": "Discuss quantities, delivery phases, site readiness, and logistics for a coordinated programme.",
    "sectorHealth": "Hospitals & healthcare",
    "detailLabel": "CONFIGURE YOUR DEVELOPMENT",
    "detailOverview": "APPLICATION OVERVIEW",
    "detailLayout": "Illustrative layout",
    "detailSpec": "Project specification",
    "detailConfigured": "Project-defined",
    "detailCapacity": "Capacity & layout",
    "detailRepeat": "Repeatable",
    "detailSystem": "Build system",
    "detailPhased": "Phased",
    "detailDelivery": "Delivery planning",
    "detailProposal": "A PROPOSAL AROUND YOUR BRIEF",
    "detailPrice": "Capacity, floor area, engineering, services, finishes, and delivery scope are reviewed for your project. Request a proposal around your intended use and programme.",
    "detailCta": "Discuss this development",
    "detailConcept": "AI-generated architectural concept · Not a completed project",
    "detailPlanNote": "Illustrative spatial relationships only. Room sizes, circulation, accessibility, engineering, and specialist requirements must be designed and approved for the project.",
    "detailConfig": "Configuration",
    "detailBuild": "Building system",
    "detailServices": "Services & infrastructure",
    "detailAccess": "Access & circulation",
    "detailScope": "Scope & approvals",
    "detailScale": "Programme & rollout",
    "detailBuildText": "FAD composite system; project engineering and specification required",
    "detailScaleText": "Quantities, phases, site readiness, and logistics agreed for the programme",
    "workersTitle": "Worker accommodation.",
    "workersAccent": "A community around the workforce.",
    "workersText": "Build a coordinated accommodation programme around occupancy, shift patterns, privacy, and shared amenities. Review repeatable rooms, communal facilities, and delivery phases as one development.",
    "workersConfig": "Room clusters and shared facilities sized around your workforce",
    "workersServices": "Water, sanitation, power, drainage, and shared amenities reviewed for the site",
    "workersAccess": "Shaded circulation, accessible routes, and emergency access reviewed in design",
    "workersScope": "Occupancy, fire safety, permits, and local requirements subject to project review",
    "workersZone1": "Accommodation",
    "workersZone2": "Accommodation",
    "workersZone3": "Accommodation",
    "workersShared": "Shared amenities & circulation",
    "schoolTitle": "Schools & learning campuses.",
    "schoolAccent": "Space for the next generation.",
    "schoolText": "Plan repeatable classrooms alongside the spaces that make a school work: circulation, support rooms, sanitation, and shared outdoor areas. Configure the campus around learning needs and enrolment plans.",
    "schoolConfig": "Classrooms, support rooms, and shared campus facilities defined by the brief",
    "schoolServices": "Sanitation, power, water, ventilation, and digital infrastructure reviewed in design",
    "schoolAccess": "Accessible circulation, supervised arrival, and emergency routes reviewed in design",
    "schoolScope": "Education standards, safety, permits, and local authority requirements to be confirmed",
    "schoolZone1": "Learning space",
    "schoolZone2": "Learning space",
    "schoolZone3": "Support rooms",
    "schoolShared": "Shared circulation & outdoor learning",
    "hospitalTitle": "Hospitals & healthcare campuses.",
    "hospitalAccent": "Infrastructure around better care.",
    "hospitalText": "Explore modular support buildings, staff accommodation, administration, and project-specific healthcare spaces. Clinical areas need specialist planning, engineering, infection-control design, and regulatory approval before specifications can be confirmed.",
    "hospitalConfig": "Support, administration, staff accommodation, or clinical spaces subject to specialist review",
    "hospitalServices": "Medical services, ventilation, sanitation, utilities, and equipment interfaces require specialist design",
    "hospitalAccess": "Patient, staff, service, and emergency routes require a clinical circulation plan",
    "hospitalScope": "Clinical suitability, infection control, fire safety, licensing, and approvals are project-specific",
    "hospitalZone1": "Support space",
    "hospitalZone2": "Administration",
    "hospitalZone3": "Reviewed use",
    "hospitalShared": "Circulation subject to clinical planning",
    "app1Jump": "Explore housing",
    "app2Jump": "Explore school facilities",
    "app3Jump": "Explore worker accommodation",
    "app4": "Hospitals & healthcare",
    "app4Tag": "HEALTHCARE & INSTITUTIONS",
    "app4Text": "Discuss support buildings and healthcare campus requirements with specialist design and approvals.",
    "app4Jump": "Explore healthcare facilities",
    "homeVisualNote": "AI-enhanced reference concept · Final design subject to project review",
    "govIntro": "FOR MINISTRIES, LOCAL GOVERNMENT & PUBLIC INSTITUTIONS",
    "govBenefit1": "A programme-level brief",
    "govBenefit1Text": "Align the intended use, capacity, sites, and delivery phases before defining the scope.",
    "govBenefit2": "A clear technical conversation",
    "govBenefit2Text": "Identify the drawings, specifications, site information, and specialist reviews needed for your project.",
    "govBenefit3": "A proposal around your process",
    "govBenefit3Text": "Share your project stage, planning year, and procurement requirements so the response fits your programme.",
    "govFormTitle": "Tell us about your government project",
    "govFormText": "Share the key details. Review your brief, then send it directly to the FAD team through WhatsApp.",
    "govName": "Contact name",
    "govAgency": "Agency / institution",
    "govEmail": "Work email",
    "govPhone": "Contact phone",
    "govLocation": "Project region / location",
    "govProgramme": "Programme type",
    "govScale": "Target units / rooms / capacity",
    "govStage": "Project stage",
    "govTimeline": "Target delivery timeline",
    "govLand": "Land / site status",
    "govYear": "Planning / fiscal year",
    "govFunding": "Funding / budget context",
    "govNote": "Project brief & document needs",
    "govConsent": "I agree to share these details with FAD to discuss this government project.",
    "govSubmit": "Prepare government project enquiry",
    "govBriefHeading": "FAD — GOVERNMENT PROJECT ENQUIRY",
    "govHousing": "Public housing",
    "govEducation": "Schools & education",
    "govAccommodation": "Worker / staff accommodation",
    "govHealthcare": "Hospitals & healthcare support",
    "govOther": "Other public facilities",
    "govPlanning": "Early planning / feasibility",
    "govScope": "Scope & budget preparation",
    "govTender": "Procurement / tender preparation",
    "govActive": "Active procurement / awarded programme",
    "govSiteReady": "Site identified / available",
    "govSiteReview": "Site under review",
    "govSitePending": "Site not yet identified",
    "govScalePlaceholder": "e.g. 500 homes, 20 classrooms, 200 beds",
    "govAgencyPlaceholder": "Ministry, regency, municipality, public institution…",
    "govLocationPlaceholder": "Province, regency / city, or site location",
    "govFundingPlaceholder": "Optional planning range or funding programme",
    "govNotePlaceholder": "Sites, delivery phases, terms of reference, drawings, specification or documentation needed…",
    "govReviewNote": "Scope, eligibility, technical requirements, and procurement documentation are reviewed for the project. This enquiry does not submit a formal tender or establish procurement qualification.",
    "preloaderTitle": "Spaces for a growing nation.",
    "preloaderText": "Housing. Communities. Public infrastructure.",
    "preloaderNote": "Illustrative architectural concepts"
  },
  "id": {
    "skip": "Langsung ke konten",
    "navSolution": "Solusi",
    "navTech": "Proyek pemerintah",
    "navProjects": "Penerapan",
    "navContact": "Konsultasikan proyek",
    "menu": "Buka menu",
    "close": "Tutup",
    "brandSub": "AFFORDABLE DEVELOPMENT",
    "group": "BAGIAN DARI GRUP",
    "heroEyebrow": "FJÄLL AFFORDABLE DEVELOPMENT",
    "heroTitle": "Bangun lebih cerdas.",
    "heroAccent": "Kembangkan skalanya.",
    "heroDescription": "Pengembangan skala besar dengan sistem yang dapat direplikasi. Dari kawasan hunian hingga akomodasi pekerja, sekolah, dan fasilitas kesehatan, selaraskan desain dan spesifikasi — lalu rencanakan pelaksanaan yang terkoordinasi.",
    "heroCta": "Mari diskusikan proyek Anda",
    "heroSecondary": "Jelajahi solusi kami",
    "heroTag": "Untuk pengembang, program pemerintah & institusi",
    "heroCaption": "ILUSTRASI KONSEP PENGEMBANGAN",
    "heroCardTitle": "Satu sistem bangun. Banyak kemungkinan.",
    "heroCardText": "Perumahan · Pendidikan · Akomodasi",
    "metric1": "Luas hunian standar",
    "metric2": "Perakitan struktur atas¹",
    "metric3": "Berat struktur ringan¹",
    "introLabel": "KEUNGGULAN FAD",
    "introTitle": "Cara membangun lebih cerdas.",
    "introAccent": "Sistem untuk skala besar.",
    "introText": "Pikirkan lebih dari satu bangunan. FAD menghadirkan sistem bangunan komposit terstandar untuk pengembangan dengan banyak unit, fungsi, dan tahap pelaksanaan. Mulai dari kebutuhan Anda. Tetapkan tata ruang, spesifikasi, dan kondisi lokasi. Susun pendekatan yang dapat direplikasi untuk seluruh program.",
    "introLink": "Jelajahi program pemerintah",
    "benefit1": "Satu standar. Setiap bangunan.",
    "benefit1Text": "Sepakati komponen, spesifikasi, dan metode perakitan sebelum pelaksanaan. Standar bersama memudahkan koordinasi program dengan banyak bangunan.",
    "benefit2": "Beragam kebutuhan. Satu sistem.",
    "benefit2Text": "Hunian, ruang kelas, fasilitas bersama, atau akomodasi: tentukan ruang berdasarkan kebutuhan penggunanya, dengan konfigurasi yang dikaji untuk setiap proyek.",
    "benefit3": "Rencanakan seluruh program.",
    "benefit3Text": "Bahas kapasitas, kesiapan lokasi, logistik, dan tahap pelaksanaan sejak awal. Pengembangan skala besar dimulai dari kebutuhan proyek yang terkoordinasi.",
    "solutionLabel": "CONTOH DESAIN YANG TERDOKUMENTASI",
    "solutionTitle": "Jelajahi titik awal.",
    "solutionAccent": "Tipe 36 adalah salah satu contoh.",
    "solutionText": "Lihat tata letak, material, dan warna hunian 36 m² yang terdokumentasi. Proyek FAD Anda dapat memiliki konfigurasi berbeda; desain, spesifikasi, dan harga dikonfirmasi melalui kajian proyek.",
    "type": "TIPE 36 / DESAIN REFERENSI",
    "concept": "Ilustrasi konsep arsitektur",
    "area": "Luas lantai",
    "rooms": "Kamar tidur",
    "panels": "Panel utama",
    "priceLabel": "PROPOSAL KHUSUS PROYEK",
    "priceNote": "Desain, spesifikasi, kondisi lokasi, logistik, dan lingkup yang disepakati menjadi dasar proposal. Diskusikan skala dan kebutuhan program Anda.",
    "colorLabel": "PILIH WARNA ANDA",
    "olive": "Hijau zaitun",
    "brown": "Cokelat bumi",
    "yellow": "Kuning keemasan",
    "purple": "Ungu royal",
    "download": "Unduh materi komersial",
    "specLink": "Diskusikan desain referensi ini",
    "techLabel": "TEKNOLOGI BANGUNAN KAMI",
    "techTitle": "Satu sistem adaptif.",
    "techAccent": "Banyak cara membangun.",
    "techText": "EPS berkepadatan tinggi, penguat fiberglass, dan resin struktural IQ membentuk sistem panel komposit FAD. Metode konstruksi konsisten untuk konfigurasi bangunan sesuai proyek.",
    "techLayer1": "Penguat fiberglass",
    "techLayer2": "Inti EPS berkepadatan tinggi",
    "techLayer3": "Ikatan resin struktural IQ",
    "techDiagram": "Ilustrasi penampang panel",
    "techStat": "Panel komposit",
    "techStatText": "Sistem bangun bersama untuk berbagai kebutuhan pengembangan",
    "tech1": "Siapkan fondasi",
    "tech1Text": "Dasar batu/blok 50 cm dengan jangkar baja, sesuai kajian teknik lokasi.",
    "tech2": "Rakit struktur",
    "tech2Text": "Hubungkan panel yang telah dipotong dengan sistem ikatan resin IQ yang ditentukan.",
    "tech3": "Lapisi & selesaikan",
    "tech3Text": "Aplikasikan matriks fiberglass dan lapisan akhir, lalu pasang pintu dan jendela UPVC.",
    "techNote": "Waktu perakitan hanya untuk struktur atas. Penyelesaian keseluruhan bergantung pada fondasi, finishing, logistik, dan kondisi lokasi.",
    "appLabel": "SOLUSI MODULAR UNTUK PENGEMBANGAN ANDA",
    "appTitle": "Ruang untuk tinggal.",
    "appAccent": "Dan kebutuhan di sekitarnya.",
    "appText": "Pilih penerapan yang sesuai program Anda. Mari diskusikan konfigurasi, spesifikasi, dan lingkup yang tepat untuk proyek Anda.",
    "app1": "Perumahan & hunian",
    "app1Tag": "PENGEMBANG & PEMERINTAH",
    "app1Text": "Dari klaster hunian hingga program satu daerah, rencanakan rumah yang dapat direplikasi sesuai ringkasan pengembangan Anda.",
    "app2": "Pendidikan & pembelajaran",
    "app2Tag": "SEKOLAH & INSTITUSI",
    "app2Text": "Diskusikan ruang kelas, fasilitas kampus, dan ruang belajar dengan tata letak sesuai kebutuhan institusi Anda.",
    "app3": "Asrama & akomodasi",
    "app3Tag": "HUNIAN PEKERJA & MAHASISWA",
    "app3Text": "Rencanakan akomodasi pekerja atau mahasiswa, dengan konfigurasi yang dikaji sesuai kapasitas dan kebutuhan lokasi.",
    "appCta": "Diskusikan solusi ini",
    "appNote": "Ilustrasi konsep arsitektur, termasuk visual dengan AI; bukan referensi proyek yang telah selesai. Desain dan lingkup akhir ditentukan sesuai proyek.",
    "governmentLabel": "PENGEMBANGAN SEKTOR PUBLIK",
    "governmentTitle": "Bangun manfaat publik.",
    "governmentAccent": "Wujudkan dalam skala besar.",
    "governmentText": "Ubah kebutuhan program menjadi diskusi pengembangan yang terkoordinasi. FAD menyesuaikan prioritas layanan publik, lokasi, target kapasitas, dan proses pengadaan Anda — dengan desain, spesifikasi, dan proposal khusus proyek.",
    "governmentCta": "Mulai kebutuhan proyek pemerintah",
    "government1": "Perencanaan skala program",
    "government2": "Kajian lingkup sesuai lokasi",
    "government3": "Dokumentasi teknis sesuai permintaan",
    "budgetLabel": "RENCANAKAN PENGEMBANGAN ANDA",
    "budgetTitle": "Mulai dari skalanya.",
    "budgetAccent": "Tentukan solusi yang tepat.",
    "budgetText": "Kawasan hunian, kampus, atau komunitas pekerja: sampaikan jumlah bangunan atau unit berulang yang Anda rencanakan. Kami akan mengkaji konfigurasi, lokasi, dan kebutuhan pelaksanaan untuk menyusun proposal khusus.",
    "budgetUnits": "Jumlah bangunan atau unit yang direncanakan",
    "budgetResult": "SKALA PROGRAM ANDA",
    "budgetRate": "unit / bangunan yang direncanakan",
    "budgetNote": "Gunakan sebagai titik awal kebutuhan proyek. Kapasitas, luas, spesifikasi teknis, lingkup, dan harga ditentukan sesuai proyek — tidak ada harga unit universal.",
    "budgetCta": "Diskusikan pengembangan saya",
    "faqLabel": "KENALI FAD LEBIH DEKAT",
    "faqTitle": "Pertanyaan Anda, terjawab.",
    "faq1": "Apakah FAD hanya untuk hunian Tipe 36?",
    "faq1Text": "Tidak. FAD adalah solusi pengembangan skala besar untuk hunian, akomodasi pekerja, dan fasilitas pendidikan, dengan fungsi kawasan kesehatan dikaji sesuai kebutuhan spesialis. Tipe 36 merupakan contoh desain referensi. Fungsi, tata ruang, dan konfigurasi lain dikaji dan ditentukan untuk setiap proyek.",
    "faq2": "Bagaimana desain ditentukan?",
    "faq2Text": "Mulai dari penggunaan, lokasi, kapasitas atau jumlah unit yang dibutuhkan, dan prioritas program. Diskusi proyek menentukan konfigurasi, kebutuhan teknis, dan lingkup sebelum proposal dikonfirmasi. Desain dan spesifikasi yang sama dapat direplikasi sesuai kebutuhan.",
    "faq3": "Bagaimana harga proyek ditentukan?",
    "faq3Text": "Setiap proposal disusun berdasarkan fungsi, konfigurasi, lokasi, rekayasa teknik, logistik, dan lingkup yang disepakati. Sampaikan kebutuhan program agar kami dapat membahas spesifikasi dan pendekatan komersial yang sesuai.",
    "faq4": "Bisakah kami meninjau laporan teknis sebelum pengadaan?",
    "faq4Text": "Ya — cantumkan kebutuhan dokumentasi teknis, pengujian, dan pengadaan dalam pertanyaan Anda. Tim dapat mendiskusikan laporan pendukung serta kesesuaiannya dengan lokasi. Desain struktural dan izin setempat harus dikonfirmasi untuk setiap proyek.",
    "contactLabel": "MARI MEMBANGUN MASA DEPAN",
    "contactTitle": "Ceritakan visi Anda.",
    "contactAccent": "Mari jelajahi kemungkinannya.",
    "contactText": "Hunian, ruang belajar, atau akomodasi — mulai dari penggunaan, lokasi, dan skala. Tim kami dapat mendiskusikan konfigurasi dan lingkup pengembangan Anda.",
    "contactDirect": "Ingin berdiskusi langsung?",
    "contactWhatsApp": "Hubungi kami di WhatsApp",
    "formTitle": "Mari diskusikan proyek Anda",
    "formSubtitle": "Bagikan kebutuhan proyek kepada tim kami melalui WhatsApp.",
    "name": "Nama lengkap",
    "namePlaceholder": "Nama lengkap Anda",
    "org": "Organisasi / institusi",
    "orgPlaceholder": "Perusahaan atau instansi pemerintah",
    "email": "Email kerja",
    "phone": "Telepon / WhatsApp",
    "location": "Lokasi proyek",
    "locationPlaceholder": "Kota / kabupaten, provinsi",
    "sector": "Jenis proyek",
    "select": "Pilih opsi",
    "sectorGov": "Program pemerintah & sektor publik",
    "sectorDev": "Pengembangan perumahan",
    "sectorEdu": "Fasilitas pendidikan",
    "sectorCorp": "Hunian pekerja / mahasiswa",
    "sectorOther": "Proyek massal lainnya",
    "units": "Estimasi jumlah unit",
    "timeline": "Target waktu",
    "timeline1": "Dalam 3 bulan",
    "timeline2": "3–6 bulan",
    "timeline3": "6–12 bulan",
    "timeline4": "Lebih dari 12 bulan",
    "timeline5": "Perencanaan awal",
    "message": "Informasi tambahan",
    "optional": "opsional",
    "messagePlaceholder": "Kesiapan lokasi, target pelaksanaan, persyaratan pengadaan atau teknis…",
    "consent": "Saya setuju membagikan informasi ini kepada Fjäll melalui WhatsApp untuk pertanyaan proyek ini.",
    "submit": "Siapkan pertanyaan proyek",
    "formNote": "Informasi Anda belum dikirim di sini. Tinjau ringkasan, lalu kirim di WhatsApp untuk menghubungi tim kami.",
    "required": "Kolom wajib",
    "footerText": "Bangun cerdas. Kembangkan skala.",
    "footerAbout": "Sistem bangunan komposit yang dapat direplikasi untuk program hunian, pendidikan, dan akomodasi.",
    "footerLinks": "JELAJAHI",
    "footerContact": "HUBUNGI",
    "footerPrivacy": "Privasi & pertanyaan",
    "footerCopyright": "© {year} Fjäll Affordable Development. Hak cipta dilindungi.",
    "footerMission": "SATU SISTEM BANGUN. BANYAK KEMUNGKINAN.",
    "reviewTitle": "Ringkasan proyek Anda siap.",
    "reviewText": "Tinjau informasi di bawah. Lanjutkan ke WhatsApp dan kirim pesan untuk menyampaikan pertanyaan Anda kepada Fjäll.",
    "reviewSend": "Lanjutkan ke WhatsApp",
    "reviewCopy": "Salin ringkasan proyek",
    "copied": "Ringkasan disalin",
    "copyError": "Tidak dapat menyalin. Pilih dan salin ringkasan di bawah.",
    "reviewEdit": "Kembali mengedit",
    "reviewNote": "Membuka WhatsApp tidak mengirim pesan secara otomatis.",
    "privacyTitle": "Pertanyaan Anda, pilihan Anda.",
    "privacyText": "Situs ini tidak mengirim informasi formulir ke server atau menyimpannya di browser. Formulir menyiapkan pesan secara lokal. Jika Anda melanjutkan, informasi dimasukkan ke tautan WhatsApp dan dikelola oleh WhatsApp serta Fjäll saat dikirim. Preferensi bahasa disimpan secara lokal. Perencana program tidak mengumpulkan informasi pribadi.",
    "privacyClose": "Mengerti",
    "briefHeading": "Fjäll Affordable Development — Pertanyaan proyek",
    "preferredLang": "Bahasa pilihan: Bahasa Indonesia",
    "imageAlt": "Konsep hunian FAD Tipe 36 dengan taman",
    "panelAlt": "Diagram tiga lapisan sistem panel komposit",
    "homeExterior": "Eksterior",
    "homePlan": "Denah",
    "homeSpec": "Spesifikasi standar",
    "homeOverview": "HUNIAN REFERENSI / TIPE 36",
    "specEyebrow": "TITIK AWAL YANG TERDEFINISI",
    "specTitle": "Spesifikasi referensi Tipe 36.",
    "specDescription": "Spesifikasi ini berlaku untuk contoh Tipe 36 dalam materi komersial. Tata letak dan program bangunan lain memerlukan spesifikasi proyek tersendiri.",
    "specItem": "Komponen",
    "specValue": "Spesifikasi standar",
    "spec1": "Konfigurasi hunian",
    "spec1Value": "36 m² · 2 kamar tidur · ruang keluarga · blok kamar mandi / dapur",
    "spec2": "Sistem panel",
    "spec2Value": "10 panel komposit utama · masing-masing 6 m × 2,4 m",
    "spec3": "Komposisi dinding",
    "spec3Value": "EPS berkepadatan tinggi, fiberglass, resin struktural IQ, dan lapisan akhir",
    "spec4": "Fondasi",
    "spec4Value": "Dasar batu / blok 50 cm dengan jangkar baja, sesuai kajian teknik lokasi",
    "spec5": "Jendela & pintu",
    "spec5Value": "Perlengkapan UPVC · 3 jendela utama + 1 jendela ventilasi atas",
    "spec6": "Warna eksterior",
    "spec6Value": "Hijau zaitun / Cokelat bumi / Kuning keemasan / Ungu royal",
    "scopeIncluded": "Cakupan referensi Tipe 36",
    "scopeIncludedText": "Fondasi batu & tangki septik; dinding & atap FAD; pintu, jendela UPVC & lapisan eksterior.",
    "scopeDeveloper": "Lingkup pengembang Tipe 36",
    "scopeDeveloperText": "Instalasi listrik & finishing interior. Cakupan akhir, perizinan setempat, logistik, dan pajak dikonfirmasi per proyek.",
    "planMaster": "Kamar tidur 01",
    "planSecond": "Kamar tidur 02",
    "planLiving": "Ruang keluarga",
    "planWet": "Kamar mandi / dapur",
    "planNote": "Ilustrasi pembagian ruang berdasarkan luas ruang dalam materi komersial. Bukaan dan susunan bersifat indikatif, sesuai kajian arsitektur dan lokasi.",
    "planCaption": "TIPE 36 / ILUSTRASI PEMBAGIAN RUANG",
    "specCta": "Diskusikan spesifikasi standar",
    "finishNote": "Empat warna. Satu desain yang dapat direplikasi.",
    "heroImageAlt": "Ilustrasi konsep pengembangan beberapa bangunan dari materi komersial Fjäll",
    "budgetBrief": "Skenario referensi Tipe 36",
    "capability1": "Perumahan",
    "capability1Text": "Hunian & program perumahan",
    "capability2": "Pendidikan",
    "capability2Text": "Sekolah & fasilitas kampus",
    "capability3": "Akomodasi",
    "capability3Text": "Komunitas pekerja & mahasiswa",
    "capability4": "Replikasi",
    "capability4Text": "Sistem bangun panel komposit",
    "journeyLabel": "LANGKAH AWAL PROYEK ANDA",
    "journeyTitle": "Proses yang jelas.",
    "journeyAccent": "Dari kebutuhan ke pembangunan.",
    "journeyDescription": "Tentukan solusi yang tepat sebelum memperbesar skala. Mulai konsultasi dengan kebutuhan proyek Anda.",
    "journey1": "Sampaikan proyek Anda",
    "journey1Text": "Ceritakan penggunaan, lokasi, skala, dan prioritas pengembangan Anda.",
    "journey2": "Selaraskan konfigurasi",
    "journey2Text": "Diskusikan tata letak, kapasitas, dan spesifikasi yang sesuai program Anda.",
    "journey3": "Kaji lokasi & lingkup",
    "journey3Text": "Konfirmasikan kebutuhan teknis, cakupan, pengadaan, dan persyaratan komersial.",
    "journey4": "Rencanakan pelaksanaan",
    "journey4Text": "Selaraskan pendekatan bangun, tahapan, dan tanggung jawab pelaksanaan yang diusulkan.",
    "journeyCta": "Mulai konsultasi",
    "preloaderLabel": "SATU SISTEM. BERAGAM KEMUNGKINAN.",
    "preloaderSkip": "Masuk ke situs",
    "filmLabel": "SISTEM FAD DALAM GERAK",
    "filmTitle": "Dari satu modul ke seluruh program.",
    "filmText": "Visual konsep arsitektur realistis memperlihatkan penerapan FAD: hunian, akomodasi pekerja, sekolah, dan fasilitas kesehatan. Ini ilustrasi konsep, bukan dokumentasi proyek yang telah selesai.",
    "offerLabel": "DARI KEBUTUHAN HINGGA PELAKSANAAN",
    "offerTitle": "Mitra pengembangan.",
    "offerAccent": "Pendekatan yang dapat direplikasi.",
    "offerText": "Mengadopsi kejelasan konstruksi modular: mulai dari fungsi, koordinasikan sistem bangunan, lalu rencanakan program. Lingkup FAD disepakati sesuai proyek Anda.",
    "offer1": "Tentukan kebutuhan ruang",
    "offer1Text": "Selaraskan fungsi, tata ruang, kapasitas, dan spesifikasi bersama untuk pengembangan Anda.",
    "offer2": "Koordinasikan pembangunan",
    "offer2Text": "Kaji sistem komposit, kebutuhan fondasi, pekerjaan lokasi, dan tanggung jawab sebelum pelaksanaan.",
    "offer3": "Rencanakan pelaksanaan",
    "offer3Text": "Diskusikan jumlah, tahap pelaksanaan, kesiapan lokasi, dan logistik untuk program yang terkoordinasi.",
    "sectorHealth": "Rumah sakit & fasilitas kesehatan",
    "detailLabel": "KONFIGURASI PENGEMBANGAN ANDA",
    "detailOverview": "GAMBARAN PENERAPAN",
    "detailLayout": "Ilustrasi tata ruang",
    "detailSpec": "Spesifikasi proyek",
    "detailConfigured": "Sesuai proyek",
    "detailCapacity": "Kapasitas & tata ruang",
    "detailRepeat": "Dapat direplikasi",
    "detailSystem": "Sistem bangunan",
    "detailPhased": "Bertahap",
    "detailDelivery": "Rencana pelaksanaan",
    "detailProposal": "PROPOSAL SESUAI KEBUTUHAN ANDA",
    "detailPrice": "Kapasitas, luas, rekayasa teknik, utilitas, finishing, dan lingkup pelaksanaan dikaji sesuai proyek. Minta proposal berdasarkan fungsi dan program Anda.",
    "detailCta": "Diskusikan pengembangan ini",
    "detailConcept": "Konsep arsitektur dengan AI · Bukan proyek yang telah selesai",
    "detailPlanNote": "Hanya ilustrasi hubungan antarruang. Ukuran ruang, sirkulasi, aksesibilitas, rekayasa teknik, dan kebutuhan khusus harus dirancang dan disetujui untuk proyek.",
    "detailConfig": "Konfigurasi",
    "detailBuild": "Sistem bangunan",
    "detailServices": "Utilitas & infrastruktur",
    "detailAccess": "Akses & sirkulasi",
    "detailScope": "Lingkup & persetujuan",
    "detailScale": "Program & pelaksanaan",
    "detailBuildText": "Sistem komposit FAD; memerlukan kajian teknik dan spesifikasi proyek",
    "detailScaleText": "Jumlah, tahap, kesiapan lokasi, dan logistik disepakati untuk program",
    "workersTitle": "Akomodasi pekerja.",
    "workersAccent": "Komunitas untuk tenaga kerja.",
    "workersText": "Susun program akomodasi yang terkoordinasi berdasarkan jumlah penghuni, pola kerja, privasi, dan fasilitas bersama. Kaji ruang yang dapat direplikasi, fasilitas komunal, dan tahap pelaksanaan sebagai satu pengembangan.",
    "workersConfig": "Kelompok kamar dan fasilitas bersama sesuai kebutuhan tenaga kerja",
    "workersServices": "Air, sanitasi, listrik, drainase, dan fasilitas bersama dikaji sesuai lokasi",
    "workersAccess": "Sirkulasi teduh, jalur aksesibel, dan akses darurat dikaji dalam desain",
    "workersScope": "Kapasitas penghuni, keselamatan kebakaran, izin, dan ketentuan setempat dikaji sesuai proyek",
    "workersZone1": "Akomodasi",
    "workersZone2": "Akomodasi",
    "workersZone3": "Akomodasi",
    "workersShared": "Fasilitas bersama & sirkulasi",
    "schoolTitle": "Sekolah & kampus pembelajaran.",
    "schoolAccent": "Ruang untuk generasi berikutnya.",
    "schoolText": "Rencanakan ruang kelas yang dapat direplikasi beserta kebutuhan sekolah: sirkulasi, ruang pendukung, sanitasi, dan area luar bersama. Konfigurasi kampus disusun sesuai kebutuhan belajar dan jumlah peserta didik.",
    "schoolConfig": "Ruang kelas, ruang pendukung, dan fasilitas kampus sesuai kebutuhan",
    "schoolServices": "Sanitasi, listrik, air, ventilasi, dan infrastruktur digital dikaji dalam desain",
    "schoolAccess": "Sirkulasi aksesibel, area kedatangan terpantau, dan jalur darurat dikaji dalam desain",
    "schoolScope": "Standar pendidikan, keselamatan, izin, dan persyaratan pemerintah setempat harus dikonfirmasi",
    "schoolZone1": "Ruang belajar",
    "schoolZone2": "Ruang belajar",
    "schoolZone3": "Ruang pendukung",
    "schoolShared": "Sirkulasi bersama & belajar luar ruang",
    "hospitalTitle": "Rumah sakit & kawasan kesehatan.",
    "hospitalAccent": "Infrastruktur untuk pelayanan.",
    "hospitalText": "Jajaki bangunan pendukung modular, akomodasi staf, administrasi, dan ruang kesehatan khusus proyek. Area klinis memerlukan perencanaan spesialis, rekayasa teknik, desain pengendalian infeksi, dan persetujuan regulasi sebelum spesifikasi dikonfirmasi.",
    "hospitalConfig": "Ruang pendukung, administrasi, akomodasi staf, atau ruang klinis sesuai kajian spesialis",
    "hospitalServices": "Utilitas medis, ventilasi, sanitasi, dan antarmuka peralatan memerlukan desain spesialis",
    "hospitalAccess": "Jalur pasien, staf, servis, dan darurat memerlukan perencanaan sirkulasi klinis",
    "hospitalScope": "Kesesuaian klinis, pengendalian infeksi, keselamatan kebakaran, izin, dan persetujuan khusus proyek",
    "hospitalZone1": "Ruang pendukung",
    "hospitalZone2": "Administrasi",
    "hospitalZone3": "Fungsi dikaji",
    "hospitalShared": "Sirkulasi sesuai perencanaan klinis",
    "app1Jump": "Jelajahi hunian",
    "app2Jump": "Jelajahi fasilitas sekolah",
    "app3Jump": "Jelajahi akomodasi pekerja",
    "app4": "Rumah sakit & fasilitas kesehatan",
    "app4Tag": "KESEHATAN & INSTITUSI",
    "app4Text": "Diskusikan bangunan pendukung dan kebutuhan kawasan kesehatan dengan desain spesialis dan persetujuan.",
    "app4Jump": "Jelajahi fasilitas kesehatan",
    "homeVisualNote": "Visual konsep referensi dengan AI · Desain akhir sesuai kajian proyek",
    "govIntro": "UNTUK KEMENTERIAN, PEMERINTAH DAERAH & INSTITUSI PUBLIK",
    "govBenefit1": "Kebutuhan pada tingkat program",
    "govBenefit1Text": "Selaraskan fungsi, kapasitas, lokasi, dan tahap pelaksanaan sebelum menentukan lingkup.",
    "govBenefit2": "Diskusi teknis yang terarah",
    "govBenefit2Text": "Identifikasi gambar, spesifikasi, informasi lokasi, dan kajian spesialis yang diperlukan untuk proyek Anda.",
    "govBenefit3": "Proposal sesuai proses Anda",
    "govBenefit3Text": "Sampaikan tahap proyek, tahun perencanaan, dan persyaratan pengadaan agar respons sesuai kebutuhan program.",
    "govFormTitle": "Ceritakan proyek pemerintah Anda",
    "govFormText": "Sampaikan informasi utama. Tinjau kebutuhan proyek, lalu kirim langsung ke tim FAD melalui WhatsApp.",
    "govName": "Nama kontak",
    "govAgency": "Instansi / lembaga",
    "govEmail": "Email kantor",
    "govPhone": "Nomor kontak",
    "govLocation": "Wilayah / lokasi proyek",
    "govProgramme": "Jenis program",
    "govScale": "Target unit / ruang / kapasitas",
    "govStage": "Tahap proyek",
    "govTimeline": "Target waktu pelaksanaan",
    "govLand": "Status lahan / lokasi",
    "govYear": "Tahun perencanaan / anggaran",
    "govFunding": "Konteks pendanaan / anggaran",
    "govNote": "Kebutuhan proyek & dokumen",
    "govConsent": "Saya setuju membagikan informasi ini kepada FAD untuk membahas proyek pemerintah ini.",
    "govSubmit": "Siapkan pertanyaan proyek pemerintah",
    "govBriefHeading": "FAD — PERTANYAAN PROYEK PEMERINTAH",
    "govHousing": "Perumahan publik",
    "govEducation": "Sekolah & pendidikan",
    "govAccommodation": "Akomodasi pekerja / staf",
    "govHealthcare": "Rumah sakit & fasilitas pendukung",
    "govOther": "Fasilitas publik lainnya",
    "govPlanning": "Perencanaan awal / studi kelayakan",
    "govScope": "Penyusunan lingkup & anggaran",
    "govTender": "Persiapan pengadaan / tender",
    "govActive": "Pengadaan aktif / program ditetapkan",
    "govSiteReady": "Lokasi telah ditentukan / tersedia",
    "govSiteReview": "Lokasi sedang dikaji",
    "govSitePending": "Lokasi belum ditentukan",
    "govScalePlaceholder": "mis. 500 hunian, 20 ruang kelas, 200 tempat tidur",
    "govAgencyPlaceholder": "Kementerian, kabupaten, kota, institusi publik…",
    "govLocationPlaceholder": "Provinsi, kabupaten / kota, atau lokasi lahan",
    "govFundingPlaceholder": "Kisaran perencanaan atau program pendanaan (opsional)",
    "govNotePlaceholder": "Lokasi, tahap pelaksanaan, kerangka acuan, gambar, spesifikasi atau dokumen yang diperlukan…",
    "govReviewNote": "Lingkup, kelayakan, persyaratan teknis, dan dokumen pengadaan dikaji sesuai proyek. Pertanyaan ini bukan pengajuan tender resmi atau pernyataan kualifikasi pengadaan.",
    "preloaderTitle": "Ruang untuk Indonesia yang berkembang.",
    "preloaderText": "Hunian. Komunitas. Infrastruktur publik.",
    "preloaderNote": "Ilustrasi konsep arsitektur"
  }
};
