export const content = {
  "en": {
    "skip": "Skip to content",
    "navSolution": "Standard home",
    "navTech": "Build system",
    "navProjects": "Developments",
    "navContact": "Plan your project",
    "menu": "Open menu",
    "close": "Close",
    "brandSub": "BY FJÄLL GROUP",
    "group": "A FJÄLL GROUP COMPANY",
    "heroEyebrow": "STANDARD HOMES. EXTRAORDINARY SCALE.",
    "heroTitle": "One standard.",
    "heroAccent": "Built at scale.",
    "heroDescription": "A repeatable home. A consistent specification. A smarter foundation for mass housing — from a planned neighbourhood to an entire district.",
    "heroCta": "Plan your development",
    "heroSecondary": "Explore the Type 36",
    "heroTag": "For developers, government & institutional partners",
    "heroCaption": "STANDARD HOME / CONCEPT VISUAL",
    "heroCardTitle": "FAD / The standard Type 36",
    "heroCardText": "36 m² · 2 bedrooms · 10 composite panels",
    "metric1": "Standard home footprint",
    "metric2": "Superstructure assembly¹",
    "metric3": "Lightweight structure¹",
    "metric4": "Baseline unit value²",
    "metricsNote": "¹ Product specifications stated in the commercial deck. ² Indicative Type 36 value; final scope and pricing subject to project review.",
    "introLabel": "01 / A REPEATABLE APPROACH",
    "introTitle": "Good design,",
    "introAccent": "multiplied.",
    "introText": "Mass-scale development starts with a clear standard. FAD brings one defined home design, a composite panel build system, and a repeatable specification to every unit — helping developers and public-sector partners plan communities with greater clarity.",
    "introLink": "See how the system works",
    "benefit1": "One standard specification",
    "benefit1Text": "A defined Type 36 footprint, component set, and material system establish a common starting point for every home.",
    "benefit2": "A repeatable build system",
    "benefit2Text": "Pre-engineered panels and a consistent assembly sequence make the same design repeatable across a development.",
    "benefit3": "Planned at programme scale",
    "benefit3Text": "Bring your unit target, site requirements, and delivery priorities. Build the project scope around a shared standard.",
    "solutionLabel": "02 / THE STANDARD HOME",
    "solutionTitle": "Meet the Type 36.",
    "solutionAccent": "Designed once. Repeated with purpose.",
    "solutionText": "A practical two-bedroom home, ready to become the building block of your development. One core specification, four exterior finishes.",
    "type": "FAD 36 / STANDARD DESIGN",
    "concept": "Concept visual · Commercial deck",
    "area": "Floor area",
    "rooms": "Bedrooms",
    "panels": "Primary panels",
    "priceLabel": "BASELINE UNIT VALUE",
    "priceNote": "Indicative commercial-deck pricing. Site works, final inclusions, taxes, transport, and project requirements to be confirmed in your proposal.",
    "colorLabel": "SELECT YOUR FINISH",
    "olive": "Olive green",
    "brown": "Earthy brown",
    "yellow": "Golden yellow",
    "purple": "Royal purple",
    "download": "Download commercial deck",
    "specLink": "Request a Type 36 proposal",
    "techLabel": "03 / THE BUILD SYSTEM",
    "techTitle": "A common system.",
    "techAccent": "From factory to site.",
    "techText": "High-density EPS, fiberglass reinforcement, and proprietary IQ structural resin form the FAD composite panel system. Standard components. A defined assembly sequence.",
    "techLayer1": "Fiberglass reinforcement",
    "techLayer2": "High-density EPS core",
    "techLayer3": "IQ structural resin bond",
    "techDiagram": "Illustrative panel cross-section",
    "techStat": "10 panels",
    "techStatText": "The starting point for a standard 36 m² unit",
    "tech1": "Prepare the foundation",
    "tech1Text": "A 50 cm stone/block base with steel anchors, subject to site engineering.",
    "tech2": "Assemble the structure",
    "tech2Text": "Connect pre-cut panels using the specified IQ resin bonding system.",
    "tech3": "Coat & finish",
    "tech3Text": "Apply the fiberglass matrix and finishes, then install UPVC doors and windows.",
    "techNote": "Assembly timing refers to the superstructure only. Overall delivery depends on foundation works, finishes, logistics, and site conditions.",
    "appLabel": "04 / DEVELOPMENT AT SCALE",
    "appTitle": "One home is a start.",
    "appAccent": "A community is the goal.",
    "appText": "For the programmes that need the same quality, specification, and design across many units.",
    "app1": "Mass residential",
    "app1Tag": "DEVELOPERS & PUBLIC HOUSING",
    "app1Text": "Repeatable homes for planned neighbourhoods and government housing programmes.",
    "app2": "Educational facilities",
    "app2Tag": "SCHOOLS & CAMPUSES",
    "app2Text": "Scalable spaces that support learning, campus expansion, and community needs.",
    "app3": "Worker & student housing",
    "app3Tag": "CORPORATE & INSTITUTIONAL",
    "app3Text": "Adaptable accommodation for workforce communities and student residences.",
    "appCta": "Plan a project",
    "appNote": "Illustrative development concepts from the commercial deck; not completed project references.",
    "governmentLabel": "GOVERNMENT & INSTITUTIONAL PROGRAMMES",
    "governmentTitle": "A shared standard.",
    "governmentAccent": "A bigger public purpose.",
    "governmentText": "Bring a housing target. We’ll discuss a repeatable Type 36 approach around your site, procurement needs, technical requirements, and programme priorities.",
    "governmentCta": "Discuss a government project",
    "government1": "Programme-scale planning",
    "government2": "Site-specific scope review",
    "government3": "Technical documentation on request",
    "budgetLabel": "05 / PROGRAMME PLANNING",
    "budgetTitle": "See the standard",
    "budgetAccent": "at your scale.",
    "budgetText": "Start with a unit target. Explore the indicative base unit budget, then discuss the site-specific scope with our project team.",
    "budgetUnits": "Number of Type 36 homes",
    "budgetResult": "INDICATIVE BASE UNIT BUDGET",
    "budgetRate": "units × Rp 50,000,000",
    "budgetNote": "Planning estimate only, based on the commercial deck. Not a quotation. Land, infrastructure, taxes, logistics, and any scope adjustments require separate confirmation.",
    "budgetCta": "Request a project proposal",
    "faqLabel": "BEFORE WE BUILD",
    "faqTitle": "The details matter.",
    "faq1": "Who is FAD designed for?",
    "faq1Text": "FAD is the mass-scale housing product of Fjäll Group, designed for developers, government housing programmes, educational institutions, and organisations planning multi-unit accommodation.",
    "faq2": "What does the 1–3 hour assembly time include?",
    "faq2Text": "The commercial deck states 1–3 hours for assembling one unit’s superstructure. It does not represent total turnkey construction time. Foundation preparation, coating, finishing, utilities, and site logistics affect the overall schedule.",
    "faq3": "Is Rp 50 million the final project price?",
    "faq3Text": "Rp 50 million is the deck’s baseline value for a standard 36 m² unit. A project proposal must confirm inclusions, developer scope, location, logistics, taxes, and technical requirements. Additional area is listed at Rp 1.4 million/m², subject to project review.",
    "faq4": "Can we review technical reports before procurement?",
    "faq4Text": "Yes — include your technical, testing, and procurement documentation needs in your enquiry. The team can discuss the supporting reports and their applicability to your site. Structural design and local approvals must be confirmed for each project.",
    "contactLabel": "06 / START THE CONVERSATION",
    "contactTitle": "Let’s build",
    "contactAccent": "your next community.",
    "contactText": "A repeatable development starts with a clear brief. Tell us where, how many units, and what your programme needs to achieve.",
    "contactDirect": "Prefer a conversation?",
    "contactWhatsApp": "Talk to us on WhatsApp",
    "formTitle": "Your development brief",
    "formSubtitle": "Share your brief with our project team via WhatsApp.",
    "name": "Full name",
    "namePlaceholder": "Your full name",
    "org": "Organisation / institution",
    "orgPlaceholder": "Company or government agency",
    "email": "Work email",
    "phone": "Phone / WhatsApp",
    "location": "Project location",
    "locationPlaceholder": "City / regency, province",
    "sector": "Project type",
    "select": "Select an option",
    "sectorGov": "Government housing programme",
    "sectorDev": "Residential development",
    "sectorEdu": "Educational facilities",
    "sectorCorp": "Worker / student housing",
    "sectorOther": "Other bulk project",
    "units": "Estimated number of units",
    "timeline": "Target timeline",
    "timeline1": "Within 3 months",
    "timeline2": "3–6 months",
    "timeline3": "6–12 months",
    "timeline4": "More than 12 months",
    "timeline5": "Early planning",
    "message": "Tell us more",
    "optional": "optional",
    "messagePlaceholder": "Site readiness, delivery goals, procurement or technical requirements…",
    "consent": "I agree to share these details with Fjäll via WhatsApp for this project enquiry.",
    "submit": "Prepare my project enquiry",
    "formNote": "Your details are not submitted here. Review your brief, then send it in WhatsApp to reach our team.",
    "required": "Required fields",
    "footerText": "One standard. More communities.",
    "footerAbout": "Advanced composite housing solutions by Fjäll Group.",
    "footerLinks": "EXPLORE",
    "footerContact": "CONNECT",
    "footerPrivacy": "Privacy & enquiries",
    "footerCopyright": "© {year} Fjäll Affordable Development. All rights reserved.",
    "footerMission": "STANDARD HOMES. SCALABLE COMMUNITIES.",
    "reviewTitle": "Your project brief is ready.",
    "reviewText": "Review your details below. Continue to WhatsApp and send the message to deliver your enquiry to Fjäll.",
    "reviewSend": "Continue to WhatsApp",
    "reviewCopy": "Copy project brief",
    "copied": "Brief copied",
    "copyError": "Unable to copy. Select and copy the brief below.",
    "reviewEdit": "Back to editing",
    "reviewNote": "Opening WhatsApp does not send the message automatically.",
    "privacyTitle": "Your enquiry, your choice.",
    "privacyText": "This website does not submit your form details to a server or store them in your browser. The enquiry form prepares a message locally. If you choose to continue, your details are included in a WhatsApp link and handled by WhatsApp and Fjäll when you send it. Only your language preference is saved in this browser. The project calculator is indicative and does not collect personal information.",
    "privacyClose": "Understood",
    "briefHeading": "Fjäll Affordable Development — Project enquiry",
    "preferredLang": "Preferred language: English",
    "imageAlt": "FAD Type 36 housing concept in a landscaped setting",
    "panelAlt": "Diagram showing three layers of the composite panel system",
    "homeExterior": "Exterior",
    "homePlan": "Floor plan",
    "homeSpec": "Standard specification",
    "homeOverview": "DESIGN OVERVIEW",
    "specEyebrow": "A DEFINED STARTING POINT",
    "specTitle": "The standard, in detail.",
    "specDescription": "The following specification is stated in the commercial deck. Final engineering and project scope are confirmed for your site.",
    "specItem": "Component",
    "specValue": "Standard specification",
    "spec1": "Home configuration",
    "spec1Value": "36 m² · 2 bedrooms · living area · integrated wet core",
    "spec2": "Panel system",
    "spec2Value": "10 primary composite panels · 6 m × 2.4 m each",
    "spec3": "Wall composition",
    "spec3Value": "High-density EPS, fiberglass, IQ structural resin, and finishing layers",
    "spec4": "Foundation",
    "spec4Value": "50 cm stone / block base with steel anchors, subject to site engineering",
    "spec5": "Windows & doors",
    "spec5Value": "UPVC fixtures · 3 main windows + 1 upper ventilation window",
    "spec6": "Exterior finishes",
    "spec6Value": "Olive green / Earthy brown / Golden yellow / Royal purple",
    "scopeIncluded": "Deck-listed inclusions",
    "scopeIncludedText": "Stone foundation & septic tank; FAD walls & roofing; UPVC doors, windows & exterior coating.",
    "scopeDeveloper": "Developer scope",
    "scopeDeveloperText": "Electrical installation & interior finishing. Final inclusions, local approvals, logistics, and taxes confirmed per project.",
    "planMaster": "Bedroom 01",
    "planSecond": "Bedroom 02",
    "planLiving": "Living area",
    "planWet": "Bath / kitchen",
    "planNote": "Illustrative zoning based on the commercial-deck room areas. Openings and arrangement are indicative, subject to architectural and site review.",
    "planCaption": "TYPE 36 / ILLUSTRATIVE ZONING",
    "specCta": "Discuss the standard specification",
    "finishNote": "Four finishes. One repeatable design."
  },
  "id": {
    "skip": "Langsung ke konten",
    "navSolution": "Hunian standar",
    "navTech": "Sistem bangun",
    "navProjects": "Pengembangan",
    "navContact": "Rencanakan proyek",
    "menu": "Buka menu",
    "close": "Tutup",
    "brandSub": "BY FJÄLL GROUP",
    "group": "BAGIAN DARI FJÄLL GROUP",
    "heroEyebrow": "HUNIAN STANDAR. SKALA LUAR BIASA.",
    "heroTitle": "Satu standar.",
    "heroAccent": "Untuk skala besar.",
    "heroDescription": "Hunian yang dapat direplikasi. Spesifikasi yang konsisten. Fondasi lebih cerdas untuk perumahan massal — dari kawasan terencana hingga seluruh daerah.",
    "heroCta": "Rencanakan pengembangan",
    "heroSecondary": "Jelajahi Tipe 36",
    "heroTag": "Untuk pengembang, pemerintah & mitra institusi",
    "heroCaption": "HUNIAN STANDAR / VISUAL KONSEP",
    "heroCardTitle": "FAD / Hunian standar Tipe 36",
    "heroCardText": "36 m² · 2 kamar tidur · 10 panel komposit",
    "metric1": "Luas hunian standar",
    "metric2": "Perakitan struktur atas¹",
    "metric3": "Berat struktur ringan¹",
    "metric4": "Nilai dasar per unit²",
    "metricsNote": "¹ Spesifikasi produk menurut materi komersial. ² Nilai indikatif Tipe 36; lingkup dan harga akhir sesuai kajian proyek.",
    "introLabel": "01 / PENDEKATAN YANG DAPAT DIREPLIKASI",
    "introTitle": "Desain yang baik,",
    "introAccent": "diperbanyak.",
    "introText": "Pengembangan skala massal dimulai dari standar yang jelas. FAD menghadirkan satu desain hunian, sistem bangun panel komposit, dan spesifikasi yang dapat direplikasi untuk setiap unit — membantu pengembang dan mitra sektor publik merencanakan komunitas dengan lebih terarah.",
    "introLink": "Kenali cara kerja sistemnya",
    "benefit1": "Satu spesifikasi standar",
    "benefit1Text": "Luas Tipe 36, komponen, dan sistem material yang terdefinisi menjadi titik awal bersama untuk setiap hunian.",
    "benefit2": "Sistem bangun yang berulang",
    "benefit2Text": "Panel pracetak dan urutan perakitan yang konsisten membuat desain yang sama dapat direplikasi di seluruh kawasan.",
    "benefit3": "Perencanaan skala program",
    "benefit3Text": "Sampaikan target unit, kebutuhan lokasi, dan prioritas pelaksanaan. Rancang lingkup proyek dengan satu standar bersama.",
    "solutionLabel": "02 / HUNIAN STANDAR",
    "solutionTitle": "Kenali Tipe 36.",
    "solutionAccent": "Satu desain. Direplikasi dengan tujuan.",
    "solutionText": "Hunian dua kamar tidur yang praktis, siap menjadi unit dasar pengembangan Anda. Satu spesifikasi inti, empat pilihan warna eksterior.",
    "type": "FAD 36 / DESAIN STANDAR",
    "concept": "Visual konsep · Materi komersial",
    "area": "Luas lantai",
    "rooms": "Kamar tidur",
    "panels": "Panel utama",
    "priceLabel": "NILAI DASAR PER UNIT",
    "priceNote": "Harga indikatif dari materi komersial. Pekerjaan lokasi, cakupan akhir, pajak, transportasi, dan kebutuhan proyek dikonfirmasi dalam proposal.",
    "colorLabel": "PILIH WARNA ANDA",
    "olive": "Hijau zaitun",
    "brown": "Cokelat bumi",
    "yellow": "Kuning keemasan",
    "purple": "Ungu royal",
    "download": "Unduh materi komersial",
    "specLink": "Minta proposal Tipe 36",
    "techLabel": "03 / SISTEM BANGUN",
    "techTitle": "Satu sistem bersama.",
    "techAccent": "Dari pabrik ke lokasi.",
    "techText": "EPS berkepadatan tinggi, penguat fiberglass, dan resin struktural IQ membentuk sistem panel komposit FAD. Komponen standar. Urutan perakitan yang terdefinisi.",
    "techLayer1": "Penguat fiberglass",
    "techLayer2": "Inti EPS berkepadatan tinggi",
    "techLayer3": "Ikatan resin struktural IQ",
    "techDiagram": "Ilustrasi penampang panel",
    "techStat": "10 panel",
    "techStatText": "Titik awal untuk unit standar 36 m²",
    "tech1": "Siapkan fondasi",
    "tech1Text": "Dasar batu/blok 50 cm dengan jangkar baja, sesuai kajian teknik lokasi.",
    "tech2": "Rakit struktur",
    "tech2Text": "Hubungkan panel yang telah dipotong dengan sistem ikatan resin IQ yang ditentukan.",
    "tech3": "Lapisi & selesaikan",
    "tech3Text": "Aplikasikan matriks fiberglass dan lapisan akhir, lalu pasang pintu dan jendela UPVC.",
    "techNote": "Waktu perakitan hanya untuk struktur atas. Penyelesaian keseluruhan bergantung pada fondasi, finishing, logistik, dan kondisi lokasi.",
    "appLabel": "04 / PENGEMBANGAN SKALA BESAR",
    "appTitle": "Satu hunian adalah awal.",
    "appAccent": "Komunitas adalah tujuannya.",
    "appText": "Untuk program yang membutuhkan kualitas, spesifikasi, dan desain yang konsisten di banyak unit.",
    "app1": "Perumahan massal",
    "app1Tag": "PENGEMBANG & PERUMAHAN PUBLIK",
    "app1Text": "Hunian yang mudah direplikasi untuk kawasan terencana dan program perumahan pemerintah.",
    "app2": "Fasilitas pendidikan",
    "app2Tag": "SEKOLAH & KAMPUS",
    "app2Text": "Ruang yang dapat dikembangkan untuk pembelajaran, perluasan kampus, dan kebutuhan masyarakat.",
    "app3": "Hunian pekerja & mahasiswa",
    "app3Tag": "KORPORASI & INSTITUSI",
    "app3Text": "Akomodasi yang adaptif untuk komunitas pekerja dan asrama mahasiswa.",
    "appCta": "Rencanakan proyek",
    "appNote": "Ilustrasi konsep pengembangan dari materi komersial; bukan referensi proyek yang telah selesai.",
    "governmentLabel": "PROGRAM PEMERINTAH & INSTITUSI",
    "governmentTitle": "Standar bersama.",
    "governmentAccent": "Manfaat publik yang lebih luas.",
    "governmentText": "Sampaikan target hunian Anda. Mari diskusikan pendekatan Tipe 36 yang dapat direplikasi sesuai lokasi, kebutuhan pengadaan, persyaratan teknis, dan prioritas program.",
    "governmentCta": "Diskusikan proyek pemerintah",
    "government1": "Perencanaan skala program",
    "government2": "Kajian lingkup sesuai lokasi",
    "government3": "Dokumentasi teknis sesuai permintaan",
    "budgetLabel": "05 / PERENCANAAN PROGRAM",
    "budgetTitle": "Lihat standar ini",
    "budgetAccent": "pada skala Anda.",
    "budgetText": "Mulai dengan target unit. Lihat estimasi anggaran dasar unit, lalu diskusikan lingkup sesuai lokasi bersama tim proyek kami.",
    "budgetUnits": "Jumlah hunian Tipe 36",
    "budgetResult": "ESTIMASI ANGGARAN DASAR UNIT",
    "budgetRate": "unit × Rp 50.000.000",
    "budgetNote": "Estimasi perencanaan dari materi komersial, bukan penawaran harga. Lahan, infrastruktur, pajak, logistik, dan penyesuaian lingkup dikonfirmasi terpisah.",
    "budgetCta": "Minta proposal proyek",
    "faqLabel": "SEBELUM MEMBANGUN",
    "faqTitle": "Detail itu penting.",
    "faq1": "Untuk siapa FAD dirancang?",
    "faq1Text": "FAD adalah produk perumahan skala massal dari Fjäll Group, dirancang untuk pengembang, program perumahan pemerintah, institusi pendidikan, dan organisasi yang merencanakan akomodasi banyak unit.",
    "faq2": "Apa yang termasuk dalam waktu perakitan 1–3 jam?",
    "faq2Text": "Materi komersial menyebutkan 1–3 jam untuk perakitan struktur atas satu unit. Ini bukan waktu konstruksi lengkap siap huni. Persiapan fondasi, pelapisan, finishing, utilitas, dan logistik lokasi memengaruhi jadwal keseluruhan.",
    "faq3": "Apakah Rp 50 juta merupakan harga akhir proyek?",
    "faq3Text": "Rp 50 juta adalah nilai dasar unit standar 36 m² dalam materi komersial. Proposal proyek harus mengonfirmasi cakupan, tanggung jawab pengembang, lokasi, logistik, pajak, dan kebutuhan teknis. Luas tambahan tercantum Rp 1,4 juta/m², sesuai kajian proyek.",
    "faq4": "Bisakah kami meninjau laporan teknis sebelum pengadaan?",
    "faq4Text": "Ya — cantumkan kebutuhan dokumentasi teknis, pengujian, dan pengadaan dalam pertanyaan Anda. Tim dapat mendiskusikan laporan pendukung serta kesesuaiannya dengan lokasi. Desain struktural dan izin setempat harus dikonfirmasi untuk setiap proyek.",
    "contactLabel": "06 / MULAI DISKUSI",
    "contactTitle": "Mari membangun",
    "contactAccent": "komunitas berikutnya.",
    "contactText": "Pengembangan yang dapat direplikasi dimulai dari ringkasan yang jelas. Sampaikan lokasi, jumlah unit, dan target program Anda.",
    "contactDirect": "Ingin berdiskusi langsung?",
    "contactWhatsApp": "Hubungi kami di WhatsApp",
    "formTitle": "Ringkasan pengembangan Anda",
    "formSubtitle": "Bagikan ringkasan proyek kepada tim kami melalui WhatsApp.",
    "name": "Nama lengkap",
    "namePlaceholder": "Nama lengkap Anda",
    "org": "Organisasi / institusi",
    "orgPlaceholder": "Perusahaan atau instansi pemerintah",
    "email": "Email kerja",
    "phone": "Telepon / WhatsApp",
    "location": "Lokasi proyek",
    "locationPlaceholder": "Kota / kabupaten, provinsi",
    "sector": "Jenis proyek",
    "select": "Pilih opsi",
    "sectorGov": "Program perumahan pemerintah",
    "sectorDev": "Pengembangan perumahan",
    "sectorEdu": "Fasilitas pendidikan",
    "sectorCorp": "Hunian pekerja / mahasiswa",
    "sectorOther": "Proyek massal lainnya",
    "units": "Estimasi jumlah unit",
    "timeline": "Target waktu",
    "timeline1": "Dalam 3 bulan",
    "timeline2": "3–6 bulan",
    "timeline3": "6–12 bulan",
    "timeline4": "Lebih dari 12 bulan",
    "timeline5": "Perencanaan awal",
    "message": "Informasi tambahan",
    "optional": "opsional",
    "messagePlaceholder": "Kesiapan lokasi, target pelaksanaan, persyaratan pengadaan atau teknis…",
    "consent": "Saya setuju membagikan informasi ini kepada Fjäll melalui WhatsApp untuk pertanyaan proyek ini.",
    "submit": "Siapkan pertanyaan proyek",
    "formNote": "Informasi Anda belum dikirim di sini. Tinjau ringkasan, lalu kirim di WhatsApp untuk menghubungi tim kami.",
    "required": "Kolom wajib",
    "footerText": "Satu standar. Lebih banyak komunitas.",
    "footerAbout": "Solusi hunian komposit canggih dari Fjäll Group.",
    "footerLinks": "JELAJAHI",
    "footerContact": "HUBUNGI",
    "footerPrivacy": "Privasi & pertanyaan",
    "footerCopyright": "© {year} Fjäll Affordable Development. Hak cipta dilindungi.",
    "footerMission": "HUNIAN STANDAR. KOMUNITAS SKALA BESAR.",
    "reviewTitle": "Ringkasan proyek Anda siap.",
    "reviewText": "Tinjau informasi di bawah. Lanjutkan ke WhatsApp dan kirim pesan untuk menyampaikan pertanyaan Anda kepada Fjäll.",
    "reviewSend": "Lanjutkan ke WhatsApp",
    "reviewCopy": "Salin ringkasan proyek",
    "copied": "Ringkasan disalin",
    "copyError": "Tidak dapat menyalin. Pilih dan salin ringkasan di bawah.",
    "reviewEdit": "Kembali mengedit",
    "reviewNote": "Membuka WhatsApp tidak mengirim pesan secara otomatis.",
    "privacyTitle": "Pertanyaan Anda, pilihan Anda.",
    "privacyText": "Situs ini tidak mengirim informasi formulir ke server atau menyimpannya di browser. Formulir menyiapkan pesan secara lokal. Jika Anda melanjutkan, informasi dimasukkan ke tautan WhatsApp dan dikelola oleh WhatsApp serta Fjäll saat dikirim. Hanya preferensi bahasa yang disimpan di browser ini. Kalkulator proyek bersifat indikatif dan tidak mengumpulkan informasi pribadi.",
    "privacyClose": "Mengerti",
    "briefHeading": "Fjäll Affordable Development — Pertanyaan proyek",
    "preferredLang": "Bahasa pilihan: Bahasa Indonesia",
    "imageAlt": "Konsep hunian FAD Tipe 36 dengan taman",
    "panelAlt": "Diagram tiga lapisan sistem panel komposit",
    "homeExterior": "Eksterior",
    "homePlan": "Denah",
    "homeSpec": "Spesifikasi standar",
    "homeOverview": "RINGKASAN DESAIN",
    "specEyebrow": "TITIK AWAL YANG TERDEFINISI",
    "specTitle": "Standar, secara terperinci.",
    "specDescription": "Spesifikasi berikut tercantum dalam materi komersial. Rekayasa akhir dan lingkup proyek dikonfirmasi sesuai lokasi Anda.",
    "specItem": "Komponen",
    "specValue": "Spesifikasi standar",
    "spec1": "Konfigurasi hunian",
    "spec1Value": "36 m² · 2 kamar tidur · ruang keluarga · blok kamar mandi / dapur",
    "spec2": "Sistem panel",
    "spec2Value": "10 panel komposit utama · masing-masing 6 m × 2,4 m",
    "spec3": "Komposisi dinding",
    "spec3Value": "EPS berkepadatan tinggi, fiberglass, resin struktural IQ, dan lapisan akhir",
    "spec4": "Fondasi",
    "spec4Value": "Dasar batu / blok 50 cm dengan jangkar baja, sesuai kajian teknik lokasi",
    "spec5": "Jendela & pintu",
    "spec5Value": "Perlengkapan UPVC · 3 jendela utama + 1 jendela ventilasi atas",
    "spec6": "Warna eksterior",
    "spec6Value": "Hijau zaitun / Cokelat bumi / Kuning keemasan / Ungu royal",
    "scopeIncluded": "Cakupan dalam materi komersial",
    "scopeIncludedText": "Fondasi batu & tangki septik; dinding & atap FAD; pintu, jendela UPVC & lapisan eksterior.",
    "scopeDeveloper": "Lingkup pengembang",
    "scopeDeveloperText": "Instalasi listrik & finishing interior. Cakupan akhir, perizinan setempat, logistik, dan pajak dikonfirmasi per proyek.",
    "planMaster": "Kamar tidur 01",
    "planSecond": "Kamar tidur 02",
    "planLiving": "Ruang keluarga",
    "planWet": "Kamar mandi / dapur",
    "planNote": "Ilustrasi pembagian ruang berdasarkan luas ruang dalam materi komersial. Bukaan dan susunan bersifat indikatif, sesuai kajian arsitektur dan lokasi.",
    "planCaption": "TIPE 36 / ILUSTRASI PEMBAGIAN RUANG",
    "specCta": "Diskusikan spesifikasi standar",
    "finishNote": "Empat warna. Satu desain yang dapat direplikasi."
  }
};
