// Lazy, local WebGPU film. WebGL and a recorded film preserve the experience elsewhere.
export function mountFadMotion(root,t){
 const canvas=root.querySelector('canvas'),video=root.querySelector('video'),status=root.querySelector('.motion-status'),play=root.querySelector('.motion-play'),replay=root.querySelector('.motion-replay'),range=root.querySelector('input'),stages=[...root.querySelectorAll('[data-motion-stage]')];
 let scene,loaded=false,inView=false,playing=false,progress=0,target=0,angle=.65,raf=0,busy=false,last=0,dirty=true,backend='video';
 const stageKeys=['motionHome','motionRepeat','motionCommunity','motionFacilities'];
 function labels(){play.textContent=t(playing?'motionPause':'motionPlay');status.textContent=t(backend==='video'?'motionFilm':'motionLive');const index=backend==='video'?3:progress<.25?0:progress<.55?1:progress<.78?2:3;stages.forEach((button,n)=>{button.setAttribute('aria-pressed',String(n===index));});root.querySelector('.motion-phase').textContent=t(stageKeys[index]);}
 function fallback(){try{scene?.dispose();}catch{}scene=null;canvas.hidden=true;video.hidden=false;root.dataset.backend='video';backend='video';range.disabled=true;stages.forEach(b=>b.disabled=true);play.hidden=replay.hidden=true;root.querySelector('.motion-controls').hidden=true;root.querySelector('.motion-stages').hidden=true;status.textContent=t('motionFilm');root.querySelector('.motion-phase').textContent=t('motionFacilities');}
 function schedule(){if(!raf&&inView&&scene&&!document.hidden)raf=requestAnimationFrame(frame);}
 async function frame(time){raf=0;if(busy||!inView||document.hidden||!scene)return;const dt=Math.min((time-last)/1000,1);last=time;if(playing){target=Math.min(1,target+dt/42);angle+=dt*Math.PI*2/42;if(target>=1)playing=false;}const delta=target-progress;progress=Math.abs(delta)<.0002?target:progress+delta*(1-Math.exp(-dt*8));
 if(dirty||playing||Math.abs(delta)>.0002){busy=true;try{await scene.render(progress,angle);root.dataset.ready='true';range.value=String(Math.round(progress*100));labels();dirty=false;}catch{fallback();}finally{busy=false;}}
 if(playing||Math.abs(target-progress)>.0002||dirty)schedule();}
 async function load(){if(loaded)return;loaded=true;status.textContent=t('motionLoading');try{const{createFadScene}=await import('../public/vendor/fad-scene.js');scene=await createFadScene(canvas,{quality:innerWidth<760?'low':'high'});backend=scene.backend;root.dataset.backend=backend;canvas.hidden=false;video.hidden=true;range.disabled=false;stages.forEach(b=>b.disabled=false);resize();scene.device?.lost.then(()=>{if(scene)fallback();});labels();schedule();}catch{fallback();}}
 function resize(){if(!scene)return;const r=root.querySelector('.motion-viewport').getBoundingClientRect();const ratio=Math.min(devicePixelRatio,1.5);scene.resize(r.width*ratio,r.height*ratio);dirty=true;schedule();}
 new ResizeObserver(resize).observe(root.querySelector('.motion-viewport'));
 new IntersectionObserver(entries=>{inView=entries[0].isIntersecting;if(inView){load();last=performance.now();schedule();}else{cancelAnimationFrame(raf);raf=0;}},{rootMargin:'100px'}).observe(root);
 play.addEventListener('click',()=>{playing=!playing;if(playing&&target>=1)target=progress=0;last=performance.now();dirty=true;labels();schedule();});replay.addEventListener('click',()=>{target=0;playing=true;dirty=true;labels();schedule();});range.addEventListener('input',()=>{playing=false;target=Number(range.value)/100;dirty=true;labels();schedule();});stages.forEach((button,n)=>button.addEventListener('click',()=>{playing=false;target=[0,.4,.65,1][n];dirty=true;labels();schedule();}));
 let down=false,x=0;canvas.addEventListener('pointerdown',e=>{down=true;x=e.clientX;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!down)return;angle-=(e.clientX-x)*.008;x=e.clientX;dirty=true;schedule();});const release=()=>{down=false;};canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();fallback();});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;}else{last=performance.now();schedule();}});document.addEventListener('fad-language-change',labels);
 root.querySelector('.motion-left').addEventListener('click',()=>{angle-=.18;dirty=true;schedule();});root.querySelector('.motion-right').addEventListener('click',()=>{angle+=.18;dirty=true;schedule();});
}
