// One shared WebGL context renders all architectural icons and the opening film.
export function createRenderer(canvas) {
 const gl=canvas.getContext('webgl',{alpha:true,antialias:true,preserveDrawingBuffer:true}); if(!gl)return null;
 const vs=`attribute vec3 position;attribute vec3 normal;uniform vec3 size,offset;uniform vec2 rotation,framing;varying float light;vec3 turn(vec3 p){float c=cos(rotation.x),s=sin(rotation.x);p=vec3(c*p.x+s*p.z,p.y,-s*p.x+c*p.z);c=cos(rotation.y);s=sin(rotation.y);return vec3(p.x,c*p.y-s*p.z,s*p.y+c*p.z);}void main(){vec3 p=turn(position*size+offset);gl_Position=vec4(p.x/framing.x,p.y/framing.y,-p.z/40.,1.);light=.52+.48*max(0.,dot(turn(normal),normalize(vec3(-.3,.7,1.))));}`;
 const fs=`precision mediump float;uniform vec3 color;varying float light;void main(){gl_FragColor=vec4(color*light,1.);}`;
 function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error('FAD shader failed');return s;}
 const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('FAD program failed');gl.useProgram(program);
 const positions=[],normals=[];
 const faces=[[[1,0,0],[[.5,-.5,-.5],[.5,.5,-.5],[.5,.5,.5],[.5,-.5,.5]]],[[-1,0,0],[[-.5,-.5,.5],[-.5,.5,.5],[-.5,.5,-.5],[-.5,-.5,-.5]]],[[0,1,0],[[-.5,.5,-.5],[-.5,.5,.5],[.5,.5,.5],[.5,.5,-.5]]],[[0,-1,0],[[-.5,-.5,.5],[-.5,-.5,-.5],[.5,-.5,-.5],[.5,-.5,.5]]],[[0,0,1],[[-.5,-.5,.5],[.5,-.5,.5],[.5,.5,.5],[-.5,.5,.5]]],[[0,0,-1],[[.5,-.5,-.5],[-.5,-.5,-.5],[-.5,.5,-.5],[.5,.5,-.5]]]];
 for(const[n,ps]of faces)for(const i of[0,1,2,0,2,3]){positions.push(...ps[i]);normals.push(...n);}
 for(const[name,data]of[['position',positions],['normal',normals]]){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);const a=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,3,gl.FLOAT,false,0,0);}
 const u=Object.fromEntries(['size','offset','rotation','framing','color'].map(k=>[k,gl.getUniformLocation(program,k)]));
 const colors={mint:[.24,.81,.68],teal:[.22,.53,.5],paper:[.89,.93,.86],dark:[.08,.22,.18],glass:[.18,.41,.37]};
 const box=(offset,size,color='mint')=>{gl.uniform3fv(u.offset,offset);gl.uniform3fv(u.size,size);gl.uniform3fv(u.color,colors[color]||color);gl.drawArrays(gl.TRIANGLES,0,36);};
 function begin(span,rotation=[-.6,.5],background=[0,0,0,0]){gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(...background);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.uniform2fv(u.rotation,rotation);gl.uniform2f(u.framing,span*canvas.width/canvas.height,span);}
 function building(x,y,z,scale=1,explode=0){const b=(dx,dy,dz,sx,sy,sz,c)=>box([x+dx*scale,y+dy*scale,z+dz*scale],[sx*scale,sy*scale,sz*scale],c);
 b(0,-.48,0,1.55,.12,1.35,'teal');b(-.65-explode,0,0,.1,.9,1.1,'paper');b(.65+explode,0,0,.1,.9,1.1,'paper');b(0,0,-.5-explode,1.3,.9,.1,'mint');
 b(-.4,.01,.5+explode,.45,.9,.1,'mint');b(.44,.01,.5+explode,.38,.9,.1,'mint');b(.08,.32,.5+explode,.33,.25,.1,'mint');b(.06,-.1,.51+explode,.29,.64,.035,'dark');b(-.42,.08,.562+explode,.23,.32,.025,'glass');b(.45,.08,.562+explode,.2,.32,.025,'glass');b(0,.53+explode,0,1.52,.14,1.3,'paper');}
 function icon(kind,time=0){begin(1.35,[-.65+Math.sin(time*.5)*.12,.5]);if(kind==='layers'){for(let n=0;n<3;n++)box([0,(n-1)*.5,0],[1.65,.12,1.25],['teal','paper','mint'][n]);}else if(kind==='grid'){for(const x of[-.48,.48])for(const z of[-.48,.48])building(x,0,z,.55);}else if(kind==='building'||kind==='school'){for(const x of[-.48,.48])building(x,0,0,.7);box([0,.6,0],[1.7,.12,1.1],'teal');}else if(kind==='hospital'){building(0,0,0,1.1);box([0,.65,0],[.25,.09,.8],'mint');box([0,.65,0],[.8,.09,.25],'mint');}else if(kind==='speed')building(0,0,0,.9,.09+.08*Math.sin(time));else building(0,0,0,1.1);}
 function scene(progress){const p=Math.max(0,Math.min(1,progress)),assembly=Math.max(0,1-p*3.5),spread=Math.max(0,Math.min(1,(p-.23)/.48));begin(2.05+spread*2.7,[-.68+p*.16,.55],[.02,.12,.11,1]);box([0,-.7,0],[10,.12,6.8],'dark');for(let i=-4;i<=4;i++)box([i,-.628,0],[.015,.006,6.6],'teal');for(let i=-3;i<=3;i++)box([0,-.628,i],[9.8,.006,.015],'teal');building(0,0,0,1.05,assembly*.8);if(spread>0)for(let r=-1;r<=1;r++)for(let col=-2;col<=2;col++){if(!r&&!col)continue;const local=Math.max(0,Math.min(1,(spread*1.7-Math.abs(col)*.13-Math.abs(r)*.12)));if(local>0)building(col*1.85,(-1+local)*1.3,r*1.8,local*.88);}}
 return{icon,scene,gl};
}
export function mountWebGLIcons(root=document){
 const nodes=[...root.querySelectorAll('[data-webgl]')];if(!nodes.length)return;const source=document.createElement('canvas');source.width=source.height=120;let renderer;try{renderer=createRenderer(source);}catch{}if(!renderer)return;
 const entries=nodes.map(node=>{const canvas=node.querySelector('canvas');canvas.width=canvas.height=120;return{node,canvas,ctx:canvas.getContext('2d'),visible:false};});const reduce=matchMedia('(prefers-reduced-motion: reduce)');let frame=0,last=0;
 function draw(time){if(time-last<65)return;last=time;for(const e of entries){if(!e.visible)continue;renderer.icon(e.node.dataset.webgl,reduce.matches?0:time/1000);e.ctx.clearRect(0,0,120,120);e.ctx.drawImage(source,0,0);e.node.dataset.rendered='webgl';}}
 function loop(time){frame=0;if(document.hidden)return;draw(time);if(!reduce.matches&&entries.some(e=>e.visible))frame=requestAnimationFrame(loop);}
 function schedule(){if(!frame&&!document.hidden)frame=requestAnimationFrame(loop);}
 const observer=new IntersectionObserver(items=>{for(const item of items)entries.find(e=>e.node===item.target).visible=item.isIntersecting;schedule();},{rootMargin:'40px'});entries.forEach(e=>observer.observe(e.node));reduce.addEventListener('change',schedule);document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(frame);frame=0;}else schedule();});
 source.addEventListener('webglcontextlost',e=>{e.preventDefault();cancelAnimationFrame(frame);frame=0;entries.forEach(e=>delete e.node.dataset.rendered);});source.addEventListener('webglcontextrestored',()=>{try{renderer=createRenderer(source);schedule();}catch{}});
}
